// packages/renderer-angular/src/lib/components/cc-accordion.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel, Action } from '../types';
import { getByPointer } from '../utils/json-pointer';

interface AccordionItem { title: string; children?: ComponentDefinition[]; }

@Component({
  selector: 'cc-accordion',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="cc-accordion" [class]="variantClass">
      @for (item of items; track $index; let i = $index) {
        <div class="cc-accordion-item">
          <button class="cc-accordion-header" [class.expanded]="isExpanded(i)" (click)="toggle(i)">
            <span>{{ item.title }}</span>
            <span class="cc-accordion-icon">{{ isExpanded(i) ? '−' : '+' }}</span>
          </button>
          @if (isExpanded(i)) {
            <div class="cc-accordion-content">
              <ng-content></ng-content>
            </div>
          }
        </div>
      }
    </div>
  `,
  styles: [`
    .cc-accordion-item { border-bottom: 1px solid #e2e8f0; }
    .cc-accordion-header {
      width: 100%; padding: 1rem; background: none; border: none;
      display: flex; justify-content: space-between; align-items: center;
      cursor: pointer; font-weight: 500; text-align: left;
    }
    .cc-accordion-header:hover { background: #f8fafc; }
    .cc-accordion-content { padding: 0 1rem 1rem; }
    .cc-accordion-bordered .cc-accordion-item { border: 1px solid #e2e8f0; border-radius: 0.5rem; margin-bottom: 0.5rem; }
    .cc-accordion-separated .cc-accordion-item { background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 0.5rem; margin-bottom: 0.5rem; border: none; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcAccordionComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();
  @Output() action = new EventEmitter<Action>();

  private expandedSet = new Set<number>();

  get items(): AccordionItem[] { return (this.component['items'] as AccordionItem[]) ?? []; }
  get allowMultiple(): boolean { return (this.component['allowMultiple'] as boolean) ?? false; }
  get expandedPath(): string | undefined { return this.component['expandedPath'] as string; }
  get variant(): string { return (this.component['variant'] as string) ?? 'default'; }
  get variantClass(): string { return `cc-accordion-${this.variant}`; }

  isExpanded(index: number): boolean { return this.expandedSet.has(index); }

  toggle(index: number): void {
    if (this.expandedSet.has(index)) {
      this.expandedSet.delete(index);
    } else {
      if (!this.allowMultiple) this.expandedSet.clear();
      this.expandedSet.add(index);
    }
    if (this.expandedPath) {
      const value = this.allowMultiple ? Array.from(this.expandedSet) : (this.expandedSet.size > 0 ? Array.from(this.expandedSet)[0] : null);
      this.inputChange.emit({ path: this.expandedPath, value });
    }
  }
}

// packages/renderer-lit/src/components/cc-accordion.ts
import { LitElement, html, css } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { AccordionComponent, AccordionItem, DataModel } from '@claude-canvas/core';
import { getByPointer, setByPointer } from '@claude-canvas/core';

@customElement('cc-accordion')
export class CcAccordion extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .accordion {
      display: flex;
      flex-direction: column;
    }

    .accordion.bordered {
      border: 1px solid var(--cc-border, #e5e7eb);
      border-radius: 8px;
      overflow: hidden;
    }

    .accordion.separated {
      gap: 8px;
    }

    .accordion-item {
      border-bottom: 1px solid var(--cc-border, #e5e7eb);
    }

    .accordion.bordered .accordion-item:last-child {
      border-bottom: none;
    }

    .accordion.separated .accordion-item {
      border: 1px solid var(--cc-border, #e5e7eb);
      border-radius: 8px;
      overflow: hidden;
    }

    .accordion-header {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 12px 16px;
      background: var(--cc-accordion-header-bg, transparent);
      border: none;
      width: 100%;
      text-align: left;
      cursor: pointer;
      transition: background 0.2s;
    }

    .accordion-header:hover {
      background: var(--cc-accordion-header-hover, rgba(0, 0, 0, 0.04));
    }

    .accordion-header:disabled {
      cursor: not-allowed;
      opacity: 0.5;
    }

    .accordion-icon {
      font-size: 1.25rem;
      flex-shrink: 0;
    }

    .accordion-title-section {
      flex: 1;
    }

    .accordion-title {
      font-size: 1rem;
      font-weight: 600;
      color: var(--cc-text-primary, #111827);
      margin: 0;
    }

    .accordion-subtitle {
      font-size: 0.875rem;
      color: var(--cc-text-secondary, #6b7280);
      margin: 4px 0 0 0;
    }

    .accordion-chevron {
      font-size: 1rem;
      color: var(--cc-text-secondary, #6b7280);
      transition: transform 0.2s;
    }

    .accordion-chevron.expanded {
      transform: rotate(180deg);
    }

    .accordion-content {
      overflow: hidden;
      max-height: 0;
      transition: max-height 0.3s ease-out;
    }

    .accordion-content.expanded {
      max-height: 1000px;
    }

    .accordion-content-inner {
      padding: 0 16px 16px 16px;
    }
  `;

  @property({ type: Object })
  component!: AccordionComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  @state()
  private localExpanded: Set<string> = new Set();

  connectedCallback() {
    super.connectedCallback();
    // Initialize with default expanded items
    this.component.items.forEach(item => {
      if (item.defaultExpanded) {
        this.localExpanded.add(item.id);
      }
    });
  }

  private getExpanded(): Set<string> {
    if (this.component.expandedPath) {
      const value = getByPointer(this.dataModel, this.component.expandedPath);
      if (Array.isArray(value)) {
        return new Set(value);
      }
    }
    return this.localExpanded;
  }

  private toggleItem(itemId: string) {
    const expanded = this.getExpanded();
    const allowMultiple = this.component.allowMultiple ?? false;

    let newExpanded: Set<string>;
    if (expanded.has(itemId)) {
      newExpanded = new Set(expanded);
      newExpanded.delete(itemId);
    } else {
      if (allowMultiple) {
        newExpanded = new Set(expanded);
        newExpanded.add(itemId);
      } else {
        newExpanded = new Set([itemId]);
      }
    }

    if (this.component.expandedPath) {
      this.dispatchEvent(new CustomEvent('cc-action', {
        bubbles: true,
        composed: true,
        detail: {
          action: { type: 'update', path: this.component.expandedPath, value: Array.from(newExpanded) },
          dataModel: this.dataModel,
        },
      }));
    } else {
      this.localExpanded = newExpanded;
      this.requestUpdate();
    }
  }

  private renderItem(item: AccordionItem) {
    const expanded = this.getExpanded();
    const isExpanded = expanded.has(item.id);

    return html`
      <div class="accordion-item">
        <button
          class="accordion-header"
          ?disabled="${item.disabled}"
          @click="${() => this.toggleItem(item.id)}"
        >
          ${item.icon ? html`<span class="accordion-icon">${item.icon}</span>` : ''}
          <div class="accordion-title-section">
            <p class="accordion-title">${item.title}</p>
            ${item.subtitle ? html`<p class="accordion-subtitle">${item.subtitle}</p>` : ''}
          </div>
          <span class="accordion-chevron ${isExpanded ? 'expanded' : ''}">▼</span>
        </button>
        <div class="accordion-content ${isExpanded ? 'expanded' : ''}">
          <div class="accordion-content-inner">
            <slot name="${item.id}"></slot>
          </div>
        </div>
      </div>
    `;
  }

  render() {
    const variant = this.component.variant ?? 'default';

    return html`
      <div class="accordion ${variant}">
        ${this.component.items.map(item => this.renderItem(item))}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-accordion': CcAccordion;
  }
}
