// packages/renderer-react/src/components/CcAccordion.tsx
import { useState, useCallback, type ReactNode } from 'react';
import type { AccordionComponent, AccordionItem, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

export interface CcAccordionProps {
  component: AccordionComponent;
  dataModel: DataModel;
  onInput: (path: string, value: unknown) => void;
  renderChildren?: (children: AccordionItem['children']) => ReactNode[];
}

export function CcAccordion({ component, dataModel, onInput, renderChildren }: CcAccordionProps) {
  const [localExpanded, setLocalExpanded] = useState<Set<string>>(() => {
    const initial = new Set<string>();
    component.items.forEach(item => {
      if (item.defaultExpanded) initial.add(item.id);
    });
    return initial;
  });

  const getExpanded = useCallback((): Set<string> => {
    if (component.expandedPath) {
      const value = getByPointer(dataModel, component.expandedPath);
      if (Array.isArray(value)) return new Set(value);
    }
    return localExpanded;
  }, [component.expandedPath, dataModel, localExpanded]);

  const toggleItem = useCallback((itemId: string) => {
    const expanded = getExpanded();
    const allowMultiple = component.allowMultiple ?? false;

    let newExpanded: Set<string>;
    if (expanded.has(itemId)) {
      newExpanded = new Set(expanded);
      newExpanded.delete(itemId);
    } else {
      newExpanded = allowMultiple ? new Set(expanded) : new Set();
      newExpanded.add(itemId);
    }

    if (component.expandedPath) {
      onInput(component.expandedPath, Array.from(newExpanded));
    } else {
      setLocalExpanded(newExpanded);
    }
  }, [getExpanded, component.allowMultiple, component.expandedPath, onInput]);

  const variant = component.variant ?? 'default';
  const expanded = getExpanded();

  const containerStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    ...(variant === 'bordered' && {
      border: '1px solid var(--cc-border, #e5e7eb)',
      borderRadius: 8,
      overflow: 'hidden',
    }),
    ...(variant === 'separated' && {
      gap: 8,
    }),
  };

  const renderItem = (item: AccordionItem, index: number) => {
    const isExpanded = expanded.has(item.id);

    const itemStyle: React.CSSProperties = {
      borderBottom: variant !== 'separated' ? '1px solid var(--cc-border, #e5e7eb)' : undefined,
      ...(variant === 'separated' && {
        border: '1px solid var(--cc-border, #e5e7eb)',
        borderRadius: 8,
        overflow: 'hidden',
      }),
    };

    // Remove border from last item in bordered variant
    if (variant === 'bordered' && index === component.items.length - 1) {
      itemStyle.borderBottom = 'none';
    }

    return (
      <div key={item.id} className="cc-accordion-item" style={itemStyle}>
        <button
          className="cc-accordion-header"
          disabled={item.disabled}
          onClick={() => toggleItem(item.id)}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 12,
            padding: '12px 16px',
            background: 'transparent',
            border: 'none',
            width: '100%',
            textAlign: 'left',
            cursor: item.disabled ? 'not-allowed' : 'pointer',
            opacity: item.disabled ? 0.5 : 1,
          }}
        >
          {item.icon && (
            <span className="cc-accordion-icon" style={{ fontSize: '1.25rem' }}>
              {item.icon}
            </span>
          )}
          <div style={{ flex: 1 }}>
            <p style={{ margin: 0, fontWeight: 600, fontSize: '1rem' }}>{item.title}</p>
            {item.subtitle && (
              <p style={{ margin: '4px 0 0', fontSize: '0.875rem', color: 'var(--cc-text-secondary, #6b7280)' }}>
                {item.subtitle}
              </p>
            )}
          </div>
          <span
            style={{
              fontSize: '0.75rem',
              color: 'var(--cc-text-secondary, #6b7280)',
              transform: isExpanded ? 'rotate(180deg)' : 'rotate(0)',
              transition: 'transform 0.2s',
            }}
          >
            ▼
          </span>
        </button>
        <div
          className="cc-accordion-content"
          style={{
            maxHeight: isExpanded ? 1000 : 0,
            overflow: 'hidden',
            transition: 'max-height 0.3s ease-out',
          }}
        >
          <div style={{ padding: '0 16px 16px' }}>
            {renderChildren ? renderChildren(item.children) : null}
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className={`cc-accordion cc-accordion-${variant}`} style={containerStyle}>
      {component.items.map((item, i) => renderItem(item, i))}
    </div>
  );
}

// packages/renderer-lit/src/components/cc-accordion.ts
import { LitElement, html, css } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { AccordionComponent, AccordionItem, DataModel } from '@claude-canvas/core';
import { getByPointer, setByPointer } from '@claude-canvas/core';

@customElement('cc-accordion')
export class CcAccordion extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .accordion {
      display: flex;
      flex-direction: column;
    }

    .accordion.bordered {
      border: 1px solid var(--cc-border, #e5e7eb);
      border-radius: 8px;
      overflow: hidden;
    }

    .accordion.separated {
      gap: 8px;
    }

    .accordion-item {
      border-bottom: 1px solid var(--cc-border, #e5e7eb);
    }

    .accordion.bordered .accordion-item:last-child {
      border-bottom: none;
    }

    .accordion.separated .accordion-item {
      border: 1px solid var(--cc-border, #e5e7eb);
      border-radius: 8px;
      overflow: hidden;
    }

    .accordion-header {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 12px 16px;
      background: var(--cc-accordion-header-bg, transparent);
      border: none;
      width: 100%;
      text-align: left;
      cursor: pointer;
      transition: background 0.2s;
    }

    .accordion-header:hover {
      background: var(--cc-accordion-header-hover, rgba(0, 0, 0, 0.04));
    }

    .accordion-header:disabled {
      cursor: not-allowed;
      opacity: 0.5;
    }

    .accordion-icon {
      font-size: 1.25rem;
      flex-shrink: 0;
    }

    .accordion-title-section {
      flex: 1;
    }

    .accordion-title {
      font-size: 1rem;
      font-weight: 600;
      color: var(--cc-text-primary, #111827);
      margin: 0;
    }

    .accordion-subtitle {
      font-size: 0.875rem;
      color: var(--cc-text-secondary, #6b7280);
      margin: 4px 0 0 0;
    }

    .accordion-chevron {
      font-size: 1rem;
      color: var(--cc-text-secondary, #6b7280);
      transition: transform 0.2s;
    }

    .accordion-chevron.expanded {
      transform: rotate(180deg);
    }

    .accordion-content {
      overflow: hidden;
      max-height: 0;
      transition: max-height 0.3s ease-out;
    }

    .accordion-content.expanded {
      max-height: 1000px;
    }

    .accordion-content-inner {
      padding: 0 16px 16px 16px;
    }
  `;

  @property({ type: Object })
  component!: AccordionComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  @state()
  private localExpanded: Set<string> = new Set();

  connectedCallback() {
    super.connectedCallback();
    // Initialize with default expanded items
    this.component.items.forEach(item => {
      if (item.defaultExpanded) {
        this.localExpanded.add(item.id);
      }
    });
  }

  private getExpanded(): Set<string> {
    if (this.component.expandedPath) {
      const value = getByPointer(this.dataModel, this.component.expandedPath);
      if (Array.isArray(value)) {
        return new Set(value);
      }
    }
    return this.localExpanded;
  }

  private toggleItem(itemId: string) {
    const expanded = this.getExpanded();
    const allowMultiple = this.component.allowMultiple ?? false;

    let newExpanded: Set<string>;
    if (expanded.has(itemId)) {
      newExpanded = new Set(expanded);
      newExpanded.delete(itemId);
    } else {
      if (allowMultiple) {
        newExpanded = new Set(expanded);
        newExpanded.add(itemId);
      } else {
        newExpanded = new Set([itemId]);
      }
    }

    if (this.component.expandedPath) {
      this.dispatchEvent(new CustomEvent('cc-action', {
        bubbles: true,
        composed: true,
        detail: {
          action: { type: 'update', path: this.component.expandedPath, value: Array.from(newExpanded) },
          dataModel: this.dataModel,
        },
      }));
    } else {
      this.localExpanded = newExpanded;
      this.requestUpdate();
    }
  }

  private renderItem(item: AccordionItem) {
    const expanded = this.getExpanded();
    const isExpanded = expanded.has(item.id);

    return html`
      <div class="accordion-item">
        <button
          class="accordion-header"
          ?disabled="${item.disabled}"
          @click="${() => this.toggleItem(item.id)}"
        >
          ${item.icon ? html`<span class="accordion-icon">${item.icon}</span>` : ''}
          <div class="accordion-title-section">
            <p class="accordion-title">${item.title}</p>
            ${item.subtitle ? html`<p class="accordion-subtitle">${item.subtitle}</p>` : ''}
          </div>
          <span class="accordion-chevron ${isExpanded ? 'expanded' : ''}">▼</span>
        </button>
        <div class="accordion-content ${isExpanded ? 'expanded' : ''}">
          <div class="accordion-content-inner">
            <slot name="${item.id}"></slot>
          </div>
        </div>
      </div>
    `;
  }

  render() {
    const variant = this.component.variant ?? 'default';

    return html`
      <div class="accordion ${variant}">
        ${this.component.items.map(item => this.renderItem(item))}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-accordion': CcAccordion;
  }
}
