// packages/renderer-angular/src/lib/components/cc-audio-player.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-audio-player',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="cc-audio">
      @if (title) { <div class="cc-audio-title">{{ title }}</div> }
      @if (src) {
        <audio [src]="src" [controls]="controls" [autoplay]="autoplay" [loop]="loop" class="cc-audio-player"></audio>
      } @else {
        <div class="cc-audio-placeholder">No audio source</div>
      }
    </div>
  `,
  styles: [`
    .cc-audio { padding: 1rem; background: #f8fafc; border-radius: 0.5rem; border: 1px solid #e2e8f0; }
    .cc-audio-title { font-weight: 500; margin-bottom: 0.5rem; }
    .cc-audio-player { width: 100%; }
    .cc-audio-placeholder { color: #64748b; font-size: 0.875rem; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcAudioPlayerComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};

  get src(): string | undefined { return this.component['srcPath'] ? getByPointer(this.dataModel, this.component['srcPath'] as string)?.toString() : this.component['src'] as string; }
  get title(): string | undefined { return this.component['title'] as string; }
  get controls(): boolean { return (this.component['controls'] as boolean) ?? true; }
  get autoplay(): boolean { return (this.component['autoplay'] as boolean) ?? false; }
  get loop(): boolean { return (this.component['loop'] as boolean) ?? false; }
}

// packages/renderer-lit/src/components/cc-audio-player.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { AudioPlayerComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-audio-player')
export class CcAudioPlayer extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .audio-wrapper {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
      padding: 1rem;
      background: var(--cc-surface-dim, #f3f4f6);
      border-radius: 0.5rem;
    }

    .audio-title {
      font-size: 0.875rem;
      font-weight: 500;
      color: var(--cc-text, #333);
    }

    audio {
      width: 100%;
      height: 40px;
    }

    .no-source {
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 1rem;
      color: var(--cc-text-secondary, #6b7280);
      font-size: 0.875rem;
    }
  `;

  @property({ type: Object })
  component!: AudioPlayerComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getSrc(): string | null {
    if (this.component.src) {
      return this.component.src;
    }
    if (this.component.srcPath) {
      const value = getByPointer(this.dataModel, this.component.srcPath);
      if (value != null && typeof value === 'string') {
        return value;
      }
    }
    return null;
  }

  render() {
    const src = this.getSrc();
    const controls = this.component.controls ?? true;

    if (!src) {
      return html`
        <div class="audio-wrapper">
          <div class="no-source">No audio source</div>
        </div>
      `;
    }

    return html`
      <div class="audio-wrapper">
        ${this.component.title
          ? html`<div class="audio-title">${this.component.title}</div>`
          : null
        }
        <audio
          src=${src}
          ?autoplay=${this.component.autoplay}
          ?controls=${controls}
          ?loop=${this.component.loop}
        ></audio>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-audio-player': CcAudioPlayer;
  }
}
