// packages/renderer-react/src/components/CcBadge.tsx
import type { BadgeComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

export interface CcBadgeProps {
  component: BadgeComponent;
  dataModel: DataModel;
}

export function CcBadge({ component, dataModel }: CcBadgeProps) {
  const getContent = (): string => {
    if (component.contentPath) {
      const val = getByPointer(dataModel, component.contentPath);
      return String(val ?? '');
    }
    return component.content ?? '';
  };

  const content = getContent();
  const variant = component.variant ?? 'default';
  const size = component.size ?? 'medium';
  const pill = component.pill ?? false;
  const dot = component.dot ?? false;

  const variantColors: Record<string, { bg: string; text: string }> = {
    default: { bg: 'var(--cc-badge-default-bg, #e5e7eb)', text: 'var(--cc-badge-default-text, #374151)' },
    success: { bg: 'var(--cc-badge-success-bg, #d1fae5)', text: 'var(--cc-badge-success-text, #065f46)' },
    warning: { bg: 'var(--cc-badge-warning-bg, #fef3c7)', text: 'var(--cc-badge-warning-text, #92400e)' },
    error: { bg: 'var(--cc-badge-error-bg, #fee2e2)', text: 'var(--cc-badge-error-text, #991b1b)' },
    info: { bg: 'var(--cc-badge-info-bg, #dbeafe)', text: 'var(--cc-badge-info-text, #1e40af)' },
  };

  const sizeStyles: Record<string, React.CSSProperties> = {
    small: { fontSize: '0.625rem', padding: dot ? '4px' : '2px 6px' },
    medium: { fontSize: '0.75rem', padding: dot ? '6px' : '4px 8px' },
    large: { fontSize: '0.875rem', padding: dot ? '8px' : '6px 12px' },
  };

  const colors = variantColors[variant] ?? variantColors.default;
  const backgroundColor = component.color ?? colors.bg;
  const color = component.textColor ?? colors.text;

  return (
    <span
      className={`cc-badge cc-badge-${variant} cc-badge-${size}`}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        backgroundColor,
        color,
        borderRadius: pill ? '9999px' : '4px',
        fontWeight: 500,
        lineHeight: 1,
        whiteSpace: 'nowrap',
        ...sizeStyles[size],
      }}
    >
      {component.icon && <span className="cc-badge-icon">{component.icon}</span>}
      {!dot && content}
    </span>
  );
}

// packages/renderer-lit/src/components/cc-badge.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { BadgeComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-badge')
export class CcBadge extends LitElement {
  static styles = css`
    :host {
      display: inline-block;
    }

    .badge {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      font-weight: 500;
      white-space: nowrap;
    }

    /* Sizes */
    .small {
      padding: 2px 6px;
      font-size: 0.625rem;
      border-radius: 4px;
    }

    .medium {
      padding: 4px 8px;
      font-size: 0.75rem;
      border-radius: 6px;
    }

    .large {
      padding: 6px 12px;
      font-size: 0.875rem;
      border-radius: 8px;
    }

    /* Pill shape */
    .pill.small { border-radius: 10px; }
    .pill.medium { border-radius: 12px; }
    .pill.large { border-radius: 16px; }

    /* Variants */
    .default {
      background: var(--cc-badge-default-bg, #e5e7eb);
      color: var(--cc-badge-default-text, #374151);
    }

    .success {
      background: var(--cc-badge-success-bg, #d1fae5);
      color: var(--cc-badge-success-text, #065f46);
    }

    .warning {
      background: var(--cc-badge-warning-bg, #fef3c7);
      color: var(--cc-badge-warning-text, #92400e);
    }

    .error {
      background: var(--cc-badge-error-bg, #fee2e2);
      color: var(--cc-badge-error-text, #991b1b);
    }

    .info {
      background: var(--cc-badge-info-bg, #dbeafe);
      color: var(--cc-badge-info-text, #1e40af);
    }

    /* Dot indicator */
    .dot {
      width: 8px;
      height: 8px;
      padding: 0;
      border-radius: 50%;
    }

    .dot.small { width: 6px; height: 6px; }
    .dot.large { width: 10px; height: 10px; }

    .icon {
      font-size: 1em;
    }
  `;

  @property({ type: Object })
  component!: BadgeComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getContent(): string {
    if (this.component.contentPath) {
      const value = getByPointer(this.dataModel, this.component.contentPath);
      return String(value ?? '');
    }
    return this.component.content ?? '';
  }

  render() {
    const content = this.getContent();
    const variant = this.component.variant ?? 'default';
    const size = this.component.size ?? 'medium';
    const pill = this.component.pill ?? false;
    const dot = this.component.dot ?? false;

    const customStyles: string[] = [];
    if (this.component.color) {
      customStyles.push(`background: ${this.component.color}`);
    }
    if (this.component.textColor) {
      customStyles.push(`color: ${this.component.textColor}`);
    }

    const classes = [
      'badge',
      variant,
      size,
      pill ? 'pill' : '',
      dot ? 'dot' : '',
    ].filter(Boolean).join(' ');

    return html`
      <span class="${classes}" style="${customStyles.join('; ')}">
        ${this.component.icon && !dot ? html`<span class="icon">${this.component.icon}</span>` : ''}
        ${!dot ? content : ''}
      </span>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-badge': CcBadge;
  }
}
