// packages/renderer-angular/src/lib/components/cc-button.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel, Action } from '../types';

@Component({
  selector: 'cc-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      [class]="buttonClass"
      [disabled]="disabled || loading"
      (click)="onClick()"
    >
      @if (loading) {
        <span class="cc-button-spinner"></span>
      } @else {
        @if (icon) {
          <span class="cc-button-icon">{{ icon }}</span>
        }
        {{ label }}
      }
    </button>
  `,
  styles: [`
    button {
      padding: 0.625rem 1.25rem;
      border-radius: 0.5rem;
      font-weight: 500;
      cursor: pointer;
      border: 1px solid transparent;
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      transition: all 0.15s;
    }
    button:disabled { opacity: 0.5; cursor: not-allowed; }
    .cc-button-primary { background: #6366f1; color: white; }
    .cc-button-primary:hover:not(:disabled) { background: #4f46e5; }
    .cc-button-secondary { background: #e2e8f0; color: #1e293b; }
    .cc-button-secondary:hover:not(:disabled) { background: #cbd5e1; }
    .cc-button-outline { background: transparent; border-color: #e2e8f0; color: #1e293b; }
    .cc-button-outline:hover:not(:disabled) { background: #f8fafc; }
    .cc-button-ghost { background: transparent; color: #1e293b; }
    .cc-button-ghost:hover:not(:disabled) { background: #f1f5f9; }
    .cc-button-danger { background: #ef4444; color: white; }
    .cc-button-danger:hover:not(:disabled) { background: #dc2626; }
    .cc-button-spinner {
      width: 1rem;
      height: 1rem;
      border: 2px solid currentColor;
      border-top-color: transparent;
      border-radius: 50%;
      animation: spin 0.75s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcButtonComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() action = new EventEmitter<Action>();

  get label(): string {
    return (this.component['label'] as string) ?? '';
  }

  get variant(): string {
    return (this.component['variant'] as string) ?? 'primary';
  }

  get disabled(): boolean {
    return (this.component['disabled'] as boolean) ?? false;
  }

  get loading(): boolean {
    return (this.component['loading'] as boolean) ?? false;
  }

  get icon(): string | undefined {
    return this.component['icon'] as string | undefined;
  }

  get buttonClass(): string {
    return `cc-button-${this.variant}`;
  }

  onClick(): void {
    const actionData = this.component['action'] as Action | undefined;
    if (actionData) {
      this.action.emit(actionData);
    }
  }
}

// packages/renderer-lit/src/components/cc-button.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import type { ButtonComponent, DataModel, Action } from '@claude-canvas/core';

@customElement('cc-button')
export class CcButton extends LitElement {
  static styles = css`
    :host {
      display: inline-block;
    }

    button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
      padding: 0.625rem 1.25rem;
      border-radius: 8px;
      font-size: 0.875rem;
      font-weight: 500;
      cursor: pointer;
      transition: all 0.15s ease;
      border: none;
      font-family: inherit;
    }

    button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    button.primary {
      background: var(--cc-primary, #0066cc);
      color: white;
    }

    button.primary:hover:not(:disabled) {
      background: var(--cc-primary-hover, #0052a3);
    }

    button.secondary {
      background: var(--cc-secondary, #e5e5e5);
      color: var(--cc-text, #333);
    }

    button.secondary:hover:not(:disabled) {
      background: var(--cc-secondary-hover, #d5d5d5);
    }

    button.outline {
      background: transparent;
      color: var(--cc-primary, #0066cc);
      border: 1px solid var(--cc-primary, #0066cc);
    }

    button.outline:hover:not(:disabled) {
      background: var(--cc-primary-light, #e6f0ff);
    }

    button.ghost {
      background: transparent;
      color: var(--cc-primary, #0066cc);
    }

    button.ghost:hover:not(:disabled) {
      background: var(--cc-ghost-hover, #f5f5f5);
    }

    button.danger {
      background: var(--cc-danger, #dc2626);
      color: white;
    }

    button.danger:hover:not(:disabled) {
      background: var(--cc-danger-hover, #b91c1c);
    }

    .loading-spinner {
      width: 1rem;
      height: 1rem;
      border: 2px solid transparent;
      border-top-color: currentColor;
      border-radius: 50%;
      animation: spin 0.75s linear infinite;
    }

    @keyframes spin {
      to { transform: rotate(360deg); }
    }
  `;

  @property({ type: Object })
  component!: ButtonComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private handleClick() {
    if (this.component.disabled || this.component.loading) return;

    const event = new CustomEvent<{ action: Action; dataModel: DataModel }>('cc-action', {
      bubbles: true,
      composed: true,
      detail: {
        action: this.component.action,
        dataModel: this.dataModel,
      },
    });
    this.dispatchEvent(event);
  }

  render() {
    const variant = this.component.variant ?? 'primary';
    const classes = {
      [variant]: true,
    };

    return html`
      <button
        class=${classMap(classes)}
        ?disabled=${this.component.disabled || this.component.loading}
        @click=${this.handleClick}
      >
        ${this.component.loading
          ? html`<span class="loading-spinner"></span>`
          : this.component.icon
            ? html`<span class="icon">${this.component.icon}</span>`
            : null
        }
        ${this.component.label}
      </button>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-button': CcButton;
  }
}
