// packages/renderer-react/src/components/CcColumn.tsx
import React, { ReactNode } from 'react';
import type { ColumnComponent, DataModel } from '@claude-canvas/core';

export interface CcColumnProps {
  component: ColumnComponent;
  dataModel: DataModel;
  children?: ReactNode;
}

function getFlexAlign(align?: string): string {
  switch (align) {
    case 'start': return 'flex-start';
    case 'end': return 'flex-end';
    case 'center': return 'center';
    case 'stretch': return 'stretch';
    default: return 'stretch';
  }
}

export function CcColumn({ component, children }: CcColumnProps) {
  const style: React.CSSProperties = {
    gap: component.gap ?? 8,
    alignItems: getFlexAlign(component.align),
  };

  return (
    <div className="cc-column" style={style}>
      {children}
    </div>
  );
}

// packages/renderer-lit/src/components/cc-column.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { ColumnComponent, DataModel, FlexAlignment } from '@claude-canvas/core';

@customElement('cc-column')
export class CcColumn extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .column {
      display: flex;
      flex-direction: column;
    }
  `;

  @property({ type: Object })
  component!: ColumnComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getAlignItems(align?: FlexAlignment): string {
    const map: Record<FlexAlignment, string> = {
      start: 'flex-start',
      center: 'center',
      end: 'flex-end',
      stretch: 'stretch',
      spaceBetween: 'space-between',
      spaceAround: 'space-around',
    };
    return map[align ?? 'stretch'];
  }

  render() {
    const style = `
      gap: ${this.component.gap ?? 0}px;
      align-items: ${this.getAlignItems(this.component.align)};
    `;

    return html`
      <div class="column" style=${style}>
        <slot></slot>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-column': CcColumn;
  }
}
