// packages/renderer-angular/src/lib/components/cc-multiple-choice.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-multiple-choice',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="cc-multiple-choice">
      @if (label) { <label class="cc-mc-label">{{ label }}</label> }
      <div class="cc-mc-options">
        @for (option of options; track option.value) {
          <button class="cc-mc-option" [class.selected]="isSelected(option.value)" [disabled]="disabled || (!isSelected(option.value) && atMaxSelections)" (click)="toggle(option.value)">
            {{ option.label }}
          </button>
        }
      </div>
    </div>
  `,
  styles: [`
    .cc-multiple-choice { display: flex; flex-direction: column; gap: 0.75rem; }
    .cc-mc-label { font-weight: 500; font-size: 0.875rem; color: #374151; }
    .cc-mc-options { display: flex; flex-wrap: wrap; gap: 0.5rem; }
    .cc-mc-option { padding: 0.5rem 1rem; border: 1px solid #e2e8f0; border-radius: 9999px; background: white; cursor: pointer; font-size: 0.875rem; transition: all 0.15s; }
    .cc-mc-option:hover:not(:disabled) { border-color: #6366f1; }
    .cc-mc-option.selected { background: #6366f1; color: white; border-color: #6366f1; }
    .cc-mc-option:disabled { opacity: 0.5; cursor: not-allowed; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcMultipleChoiceComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();

  get valuePath(): string | undefined { return this.component['valuePath'] as string; }
  get selectedValues(): string[] {
    if (!this.valuePath) return [];
    const v = getByPointer(this.dataModel, this.valuePath);
    return Array.isArray(v) ? v.map(x => x.toString()) : [];
  }
  get label(): string | undefined { return this.component['label'] as string; }
  get options(): Array<{ label: string; value: string }> { return (this.component['options'] as any[]) ?? []; }
  get maxSelections(): number | undefined { return this.component['maxSelections'] as number; }
  get disabled(): boolean { return (this.component['disabled'] as boolean) ?? false; }
  get atMaxSelections(): boolean { return this.maxSelections !== undefined && this.selectedValues.length >= this.maxSelections; }

  isSelected(value: string): boolean { return this.selectedValues.includes(value); }

  toggle(value: string): void {
    if (!this.valuePath) return;
    const newValues = this.isSelected(value)
      ? this.selectedValues.filter(v => v !== value)
      : [...this.selectedValues, value];
    this.inputChange.emit({ path: this.valuePath, value: newValues });
  }
}

// packages/renderer-lit/src/components/cc-multiple-choice.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { MultipleChoiceComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-multiple-choice')
export class CcMultipleChoice extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .multiple-choice-wrapper {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    label.group-label {
      font-size: 0.875rem;
      font-weight: 500;
      color: var(--cc-text, #333);
      margin-bottom: 0.25rem;
    }

    .options-list {
      display: flex;
      flex-direction: column;
      gap: 0.375rem;
    }

    .option {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.5rem 0.75rem;
      background: var(--cc-surface, white);
      border: 1px solid var(--cc-border, #d1d5db);
      border-radius: 0.375rem;
      cursor: pointer;
      transition: background-color 0.15s, border-color 0.15s;
    }

    .option:hover:not(.disabled) {
      background: var(--cc-surface-dim, #f9fafb);
    }

    .option.selected {
      border-color: var(--cc-primary, #6366f1);
      background: rgba(99, 102, 241, 0.05);
    }

    .option.disabled {
      opacity: 0.6;
      cursor: not-allowed;
    }

    .option input[type="checkbox"] {
      width: 1rem;
      height: 1rem;
      accent-color: var(--cc-primary, #6366f1);
      cursor: inherit;
    }

    .option-label {
      font-size: 0.875rem;
      color: var(--cc-text, #333);
    }

    .selection-info {
      font-size: 0.75rem;
      color: var(--cc-text-secondary, #6b7280);
    }
  `;

  @property({ type: Object })
  component!: MultipleChoiceComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getSelectedValues(): string[] {
    const value = getByPointer(this.dataModel, this.component.valuePath);
    if (Array.isArray(value)) {
      return value.filter((v): v is string => typeof v === 'string');
    }
    return [];
  }

  private handleOptionClick(optionValue: string) {
    if (this.component.disabled) return;

    const currentValues = this.getSelectedValues();
    const isSelected = currentValues.includes(optionValue);
    let newValues: string[];

    if (isSelected) {
      // Remove the value
      newValues = currentValues.filter(v => v !== optionValue);
    } else {
      // Add the value (if within max limit)
      const maxSelections = this.component.maxSelections;
      if (maxSelections && currentValues.length >= maxSelections) {
        // At max, don't add more
        return;
      }
      newValues = [...currentValues, optionValue];
    }

    const event = new CustomEvent('cc-input', {
      bubbles: true,
      composed: true,
      detail: {
        path: this.component.valuePath,
        value: newValues,
      },
    });
    this.dispatchEvent(event);
  }

  render() {
    const selectedValues = this.getSelectedValues();
    const options = this.component.options || [];
    const maxSelections = this.component.maxSelections;

    return html`
      <div class="multiple-choice-wrapper">
        ${this.component.label
          ? html`<label class="group-label">${this.component.label}</label>`
          : null
        }
        ${maxSelections
          ? html`<span class="selection-info">Select up to ${maxSelections} options (${selectedValues.length} selected)</span>`
          : null
        }
        <div class="options-list">
          ${options.map(option => {
            const isSelected = selectedValues.includes(option.value);
            const isDisabled = this.component.disabled ||
              (!isSelected && maxSelections && selectedValues.length >= maxSelections);

            return html`
              <div
                class="option ${isSelected ? 'selected' : ''} ${isDisabled ? 'disabled' : ''}"
                @click=${() => this.handleOptionClick(option.value)}
              >
                <input
                  type="checkbox"
                  .checked=${isSelected}
                  ?disabled=${isDisabled}
                  @click=${(e: Event) => e.stopPropagation()}
                  @change=${() => this.handleOptionClick(option.value)}
                />
                <span class="option-label">${option.label}</span>
              </div>
            `;
          })}
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-multiple-choice': CcMultipleChoice;
  }
}
