// packages/renderer-react/src/components/CcProgress.tsx
import type { ProgressComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

export interface CcProgressProps {
  component: ProgressComponent;
  dataModel: DataModel;
}

export function CcProgress({ component, dataModel }: CcProgressProps) {
  const getValue = (): number | undefined => {
    if (component.valuePath) {
      const val = getByPointer(dataModel, component.valuePath);
      return typeof val === 'number' ? val : undefined;
    }
    return component.value;
  };

  const value = getValue();
  const variant = component.variant ?? 'linear';
  const size = component.size ?? 'medium';
  const isIndeterminate = value === undefined;
  const showLabel = component.showLabel ?? false;

  const sizeMap = {
    small: variant === 'linear' ? 4 : 24,
    medium: variant === 'linear' ? 8 : 40,
    large: variant === 'linear' ? 12 : 56,
  };

  const sizePx = sizeMap[size];
  const color = component.color ?? 'var(--cc-primary, #3b82f6)';
  const trackColor = component.trackColor ?? 'var(--cc-progress-track, #e5e7eb)';

  if (variant === 'circular') {
    const strokeWidth = size === 'small' ? 3 : size === 'large' ? 5 : 4;
    const radius = (sizePx - strokeWidth) / 2;
    const circumference = 2 * Math.PI * radius;
    const offset = isIndeterminate ? 0 : circumference - (circumference * (value ?? 0)) / 100;

    return (
      <div
        className={`cc-progress cc-progress-circular cc-progress-${size}`}
        role="progressbar"
        aria-valuenow={isIndeterminate ? undefined : value}
        aria-valuemin={0}
        aria-valuemax={100}
        style={{
          width: sizePx,
          height: sizePx,
          position: 'relative',
        }}
      >
        <svg
          width={sizePx}
          height={sizePx}
          style={{
            transform: 'rotate(-90deg)',
            animation: isIndeterminate ? 'cc-spin 1s linear infinite' : undefined,
          }}
        >
          <circle
            cx={sizePx / 2}
            cy={sizePx / 2}
            r={radius}
            fill="none"
            stroke={trackColor}
            strokeWidth={strokeWidth}
          />
          <circle
            cx={sizePx / 2}
            cy={sizePx / 2}
            r={radius}
            fill="none"
            stroke={color}
            strokeWidth={strokeWidth}
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap="round"
            style={{
              transition: isIndeterminate ? undefined : 'stroke-dashoffset 0.3s ease',
            }}
          />
        </svg>
        {showLabel && !isIndeterminate && (
          <span
            style={{
              position: 'absolute',
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              fontSize: size === 'small' ? '0.5rem' : size === 'large' ? '0.875rem' : '0.625rem',
              fontWeight: 600,
            }}
          >
            {component.label ?? `${Math.round(value ?? 0)}%`}
          </span>
        )}
      </div>
    );
  }

  // Linear variant
  return (
    <div
      className={`cc-progress cc-progress-linear cc-progress-${size}`}
      role="progressbar"
      aria-valuenow={isIndeterminate ? undefined : value}
      aria-valuemin={0}
      aria-valuemax={100}
      style={{
        width: '100%',
        height: sizePx,
        backgroundColor: trackColor,
        borderRadius: sizePx / 2,
        overflow: 'hidden',
        position: 'relative',
      }}
    >
      <div
        style={{
          height: '100%',
          backgroundColor: color,
          borderRadius: sizePx / 2,
          transition: isIndeterminate ? undefined : 'width 0.3s ease',
          width: isIndeterminate ? '30%' : `${value}%`,
          animation: isIndeterminate ? 'cc-indeterminate 1.5s ease-in-out infinite' : undefined,
        }}
      />
      {showLabel && !isIndeterminate && (
        <span
          style={{
            position: 'absolute',
            right: 8,
            top: '50%',
            transform: 'translateY(-50%)',
            fontSize: '0.75rem',
            fontWeight: 500,
          }}
        >
          {component.label ?? `${Math.round(value ?? 0)}%`}
        </span>
      )}
    </div>
  );
}

// packages/renderer-lit/src/components/cc-progress.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { ProgressComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-progress')
export class CcProgress extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .progress-container {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .progress-label {
      font-size: 0.875rem;
      color: var(--cc-text-secondary, #666);
    }

    /* Linear Progress */
    .linear {
      width: 100%;
      height: 8px;
      background: var(--cc-progress-track, #e0e0e0);
      border-radius: 4px;
      overflow: hidden;
    }

    .linear-fill {
      height: 100%;
      background: var(--cc-progress-fill, #6366f1);
      border-radius: 4px;
      transition: width 0.3s ease;
    }

    .linear-indeterminate .linear-fill {
      width: 30%;
      animation: linear-indeterminate 1.5s ease-in-out infinite;
    }

    @keyframes linear-indeterminate {
      0% { transform: translateX(-100%); }
      100% { transform: translateX(400%); }
    }

    /* Circular Progress */
    .circular {
      position: relative;
      display: inline-flex;
      align-items: center;
      justify-content: center;
    }

    .circular svg {
      transform: rotate(-90deg);
    }

    .circular-track {
      fill: none;
      stroke: var(--cc-progress-track, #e0e0e0);
    }

    .circular-fill {
      fill: none;
      stroke: var(--cc-progress-fill, #6366f1);
      stroke-linecap: round;
      transition: stroke-dashoffset 0.3s ease;
    }

    .circular-indeterminate .circular-fill {
      animation: circular-indeterminate 1.5s ease-in-out infinite;
    }

    @keyframes circular-indeterminate {
      0% { stroke-dashoffset: 280; transform: rotate(0deg); }
      50% { stroke-dashoffset: 75; }
      100% { stroke-dashoffset: 280; transform: rotate(360deg); }
    }

    .circular-label {
      position: absolute;
      font-size: 0.75rem;
      font-weight: 600;
      color: var(--cc-text-primary, #333);
    }

    /* Sizes */
    .small .linear { height: 4px; }
    .medium .linear { height: 8px; }
    .large .linear { height: 12px; }

    .small.circular { width: 32px; height: 32px; }
    .medium.circular { width: 48px; height: 48px; }
    .large.circular { width: 64px; height: 64px; }

    .small .circular-label { font-size: 0.625rem; }
    .medium .circular-label { font-size: 0.75rem; }
    .large .circular-label { font-size: 0.875rem; }
  `;

  @property({ type: Object })
  component!: ProgressComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getValue(): number | undefined {
    if (this.component.valuePath) {
      const value = getByPointer(this.dataModel, this.component.valuePath);
      return typeof value === 'number' ? value : undefined;
    }
    return this.component.value;
  }

  private getSize(): string {
    return this.component.size ?? 'medium';
  }

  private getSizePixels(): number {
    const size = this.getSize();
    switch (size) {
      case 'small': return 32;
      case 'large': return 64;
      default: return 48;
    }
  }

  private renderLinear(value: number | undefined) {
    const isIndeterminate = value === undefined;
    const trackColor = this.component.trackColor ?? 'var(--cc-progress-track, #e0e0e0)';
    const fillColor = this.component.color ?? 'var(--cc-progress-fill, #6366f1)';

    return html`
      <div class="linear ${isIndeterminate ? 'linear-indeterminate' : ''}"
           style="background: ${trackColor}">
        <div class="linear-fill"
             style="width: ${isIndeterminate ? '30%' : `${value}%`}; background: ${fillColor}">
        </div>
      </div>
    `;
  }

  private renderCircular(value: number | undefined) {
    const isIndeterminate = value === undefined;
    const size = this.getSizePixels();
    const strokeWidth = size < 40 ? 3 : 4;
    const radius = (size - strokeWidth * 2) / 2;
    const circumference = 2 * Math.PI * radius;
    const offset = isIndeterminate ? 0 : circumference - (value! / 100) * circumference;

    const trackColor = this.component.trackColor ?? 'var(--cc-progress-track, #e0e0e0)';
    const fillColor = this.component.color ?? 'var(--cc-progress-fill, #6366f1)';

    return html`
      <div class="circular ${isIndeterminate ? 'circular-indeterminate' : ''}"
           style="width: ${size}px; height: ${size}px">
        <svg width="${size}" height="${size}">
          <circle class="circular-track"
                  cx="${size / 2}" cy="${size / 2}" r="${radius}"
                  stroke-width="${strokeWidth}"
                  style="stroke: ${trackColor}" />
          <circle class="circular-fill"
                  cx="${size / 2}" cy="${size / 2}" r="${radius}"
                  stroke-width="${strokeWidth}"
                  stroke-dasharray="${circumference}"
                  stroke-dashoffset="${offset}"
                  style="stroke: ${fillColor}; transform-origin: center;" />
        </svg>
        ${this.component.showLabel && !isIndeterminate ? html`
          <span class="circular-label">${Math.round(value!)}%</span>
        ` : ''}
      </div>
    `;
  }

  render() {
    const value = this.getValue();
    const variant = this.component.variant ?? 'linear';
    const size = this.getSize();
    const label = this.component.label ?? (this.component.showLabel && value !== undefined ? `${Math.round(value)}%` : '');

    return html`
      <div class="progress-container ${size}">
        ${variant === 'linear' ? this.renderLinear(value) : this.renderCircular(value)}
        ${variant === 'linear' && label ? html`<span class="progress-label">${label}</span>` : ''}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-progress': CcProgress;
  }
}
