// packages/renderer-angular/src/lib/components/cc-toast.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel, Action } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-toast',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (isOpen && !dismissed) {
      <div class="cc-toast" [class]="variantClass">
        <span class="cc-toast-icon">{{ icon }}</span>
        <span class="cc-toast-message">{{ message }}</span>
        @if (actionLabel) { <button class="cc-toast-action" (click)="onAction()">{{ actionLabel }}</button> }
        @if (dismissible) { <button class="cc-toast-close" (click)="dismiss()">×</button> }
      </div>
    }
  `,
  styles: [`
    .cc-toast { display: flex; align-items: center; gap: 0.75rem; padding: 0.75rem 1rem; border-radius: 0.5rem; margin: 0.5rem 0; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    .cc-toast-info { background: #dbeafe; color: #1e40af; }
    .cc-toast-success { background: #dcfce7; color: #166534; }
    .cc-toast-warning { background: #fef3c7; color: #92400e; }
    .cc-toast-error { background: #fee2e2; color: #b91c1c; }
    .cc-toast-message { flex: 1; }
    .cc-toast-action { background: none; border: none; font-weight: 600; cursor: pointer; color: inherit; text-decoration: underline; }
    .cc-toast-close { background: none; border: none; font-size: 1.25rem; cursor: pointer; color: inherit; opacity: 0.7; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcToastComponent implements OnInit, OnDestroy {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();
  @Output() action = new EventEmitter<Action>();

  dismissed = false;
  private timeoutId?: ReturnType<typeof setTimeout>;

  get openPath(): string | undefined { return this.component['openPath'] as string; }
  get isOpen(): boolean { return this.openPath ? getByPointer(this.dataModel, this.openPath) === true : true; }
  get message(): string {
    if (this.component['messagePath']) return getByPointer(this.dataModel, this.component['messagePath'] as string)?.toString() ?? '';
    return (this.component['message'] as string) ?? '';
  }
  get variant(): string { return (this.component['variant'] as string) ?? 'info'; }
  get variantClass(): string { return `cc-toast-${this.variant}`; }
  get dismissible(): boolean { return (this.component['dismissible'] as boolean) ?? true; }
  get duration(): number { return (this.component['duration'] as number) ?? 5000; }
  get actionLabel(): string | undefined { return this.component['actionLabel'] as string; }
  get icon(): string {
    const icons: Record<string, string> = { info: 'ℹ', success: '✓', warning: '⚠', error: '✕' };
    return icons[this.variant] ?? 'ℹ';
  }

  ngOnInit(): void {
    if (this.duration > 0) { this.timeoutId = setTimeout(() => this.dismiss(), this.duration); }
  }

  ngOnDestroy(): void { if (this.timeoutId) clearTimeout(this.timeoutId); }

  dismiss(): void {
    this.dismissed = true;
    if (this.openPath) { this.inputChange.emit({ path: this.openPath, value: false }); }
  }

  onAction(): void {
    const actionData = this.component['action'] as Action | undefined;
    if (actionData) { this.action.emit(actionData); }
  }
}

// packages/renderer-lit/src/components/cc-toast.ts
import { LitElement, html, css } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { ToastComponent, DataModel, Action } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-toast')
export class CcToast extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .toast-container {
      position: fixed;
      z-index: 10000;
      pointer-events: none;
    }

    /* Positions */
    .top { top: 16px; left: 50%; transform: translateX(-50%); }
    .top-left { top: 16px; left: 16px; }
    .top-right { top: 16px; right: 16px; }
    .bottom { bottom: 16px; left: 50%; transform: translateX(-50%); }
    .bottom-left { bottom: 16px; left: 16px; }
    .bottom-right { bottom: 16px; right: 16px; }

    .toast {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 12px 16px;
      border-radius: 8px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
      pointer-events: auto;
      min-width: 280px;
      max-width: 400px;
      animation: toast-in 0.3s ease-out;
    }

    .toast.hiding {
      animation: toast-out 0.3s ease-in forwards;
    }

    @keyframes toast-in {
      from {
        opacity: 0;
        transform: translateY(-20px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }

    @keyframes toast-out {
      from {
        opacity: 1;
        transform: translateY(0);
      }
      to {
        opacity: 0;
        transform: translateY(-20px);
      }
    }

    /* Variants */
    .info {
      background: var(--cc-toast-info-bg, #dbeafe);
      color: var(--cc-toast-info-text, #1e40af);
    }

    .success {
      background: var(--cc-toast-success-bg, #d1fae5);
      color: var(--cc-toast-success-text, #065f46);
    }

    .warning {
      background: var(--cc-toast-warning-bg, #fef3c7);
      color: var(--cc-toast-warning-text, #92400e);
    }

    .error {
      background: var(--cc-toast-error-bg, #fee2e2);
      color: var(--cc-toast-error-text, #991b1b);
    }

    .icon {
      font-size: 1.25rem;
      flex-shrink: 0;
    }

    .message {
      flex: 1;
      font-size: 0.875rem;
      font-weight: 500;
    }

    .action-btn {
      background: transparent;
      border: none;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 0.875rem;
      font-weight: 600;
      cursor: pointer;
      color: inherit;
      opacity: 0.8;
    }

    .action-btn:hover {
      opacity: 1;
      background: rgba(0, 0, 0, 0.1);
    }

    .close-btn {
      background: transparent;
      border: none;
      padding: 4px;
      cursor: pointer;
      color: inherit;
      opacity: 0.6;
      font-size: 1.25rem;
      line-height: 1;
    }

    .close-btn:hover {
      opacity: 1;
    }

    .hidden {
      display: none;
    }
  `;

  @property({ type: Object })
  component!: ToastComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  @state()
  private hiding = false;

  private autoHideTimeout?: ReturnType<typeof setTimeout>;

  private getIcon(): string {
    const variant = this.component.variant ?? 'info';
    const icons: Record<string, string> = {
      info: 'ℹ️',
      success: '✅',
      warning: '⚠️',
      error: '❌',
    };
    return icons[variant];
  }

  private getMessage(): string {
    if (this.component.messagePath) {
      const value = getByPointer(this.dataModel, this.component.messagePath);
      return String(value ?? '');
    }
    return this.component.message ?? '';
  }

  private isOpen(): boolean {
    const value = getByPointer(this.dataModel, this.component.openPath);
    return Boolean(value);
  }

  private handleDismiss() {
    this.hiding = true;
    setTimeout(() => {
      this.dispatchEvent(new CustomEvent('cc-action', {
        bubbles: true,
        composed: true,
        detail: {
          action: { type: 'update', path: this.component.openPath, value: false },
          dataModel: this.dataModel,
        },
      }));
      this.hiding = false;
    }, 300);
  }

  private handleAction() {
    if (this.component.action) {
      this.dispatchEvent(new CustomEvent('cc-action', {
        bubbles: true,
        composed: true,
        detail: {
          action: this.component.action,
          dataModel: this.dataModel,
        },
      }));
    }
  }

  updated(changedProperties: Map<string, unknown>) {
    super.updated(changedProperties);

    // Handle auto-dismiss
    const duration = this.component.duration ?? 5000;
    if (duration > 0 && this.isOpen() && !this.hiding) {
      if (this.autoHideTimeout) {
        clearTimeout(this.autoHideTimeout);
      }
      this.autoHideTimeout = setTimeout(() => {
        this.handleDismiss();
      }, duration);
    }
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    if (this.autoHideTimeout) {
      clearTimeout(this.autoHideTimeout);
    }
  }

  render() {
    const isOpen = this.isOpen();
    const variant = this.component.variant ?? 'info';
    const position = this.component.position ?? 'top';
    const dismissible = this.component.dismissible ?? true;
    const message = this.getMessage();
    const icon = this.getIcon();

    const positionClass = position.replace('-', '-');

    return html`
      <div class="toast-container ${positionClass} ${isOpen ? '' : 'hidden'}">
        <div class="toast ${variant} ${this.hiding ? 'hiding' : ''}">
          <span class="icon">${icon}</span>
          <span class="message">${message}</span>
          ${this.component.actionLabel ? html`
            <button class="action-btn" @click="${this.handleAction}">
              ${this.component.actionLabel}
            </button>
          ` : ''}
          ${dismissible ? html`
            <button class="close-btn" @click="${this.handleDismiss}">×</button>
          ` : ''}
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-toast': CcToast;
  }
}
