// packages/renderer-angular/src/lib/components/cc-alert.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-alert',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (isOpen && !dismissed) {
      <div class="cc-alert" [class]="variantClass">
        @if (showIcon) { <span class="cc-alert-icon">{{ icon }}</span> }
        <div class="cc-alert-content">
          @if (title) { <div class="cc-alert-title">{{ title }}</div> }
          @if (message) { <div class="cc-alert-message">{{ message }}</div> }
        </div>
        @if (dismissible) { <button class="cc-alert-close" (click)="dismiss()">×</button> }
      </div>
    }
  `,
  styles: [`
    .cc-alert { display: flex; gap: 0.75rem; padding: 1rem; border-radius: 0.5rem; border: 1px solid; }
    .cc-alert-info { background: #dbeafe; border-color: #93c5fd; color: #1e40af; }
    .cc-alert-success { background: #dcfce7; border-color: #86efac; color: #166534; }
    .cc-alert-warning { background: #fef3c7; border-color: #fcd34d; color: #92400e; }
    .cc-alert-error { background: #fee2e2; border-color: #fca5a5; color: #b91c1c; }
    .cc-alert-icon { font-size: 1.25rem; }
    .cc-alert-content { flex: 1; }
    .cc-alert-title { font-weight: 600; margin-bottom: 0.25rem; }
    .cc-alert-close { background: none; border: none; font-size: 1.25rem; cursor: pointer; color: inherit; opacity: 0.7; align-self: flex-start; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcAlertComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();

  dismissed = false;

  get openPath(): string | undefined { return this.component['openPath'] as string; }
  get isOpen(): boolean { return this.openPath ? getByPointer(this.dataModel, this.openPath) !== false : true; }
  get message(): string {
    if (this.component['messagePath']) return getByPointer(this.dataModel, this.component['messagePath'] as string)?.toString() ?? '';
    return (this.component['message'] as string) ?? '';
  }
  get title(): string | undefined { return this.component['title'] as string; }
  get variant(): string { return (this.component['variant'] as string) ?? 'info'; }
  get variantClass(): string { return `cc-alert-${this.variant}`; }
  get showIcon(): boolean { return (this.component['showIcon'] as boolean) ?? true; }
  get dismissible(): boolean { return (this.component['dismissible'] as boolean) ?? false; }
  get icon(): string {
    const icons: Record<string, string> = { info: 'ℹ', success: '✓', warning: '⚠', error: '✕' };
    return icons[this.variant] ?? 'ℹ';
  }

  dismiss(): void {
    this.dismissed = true;
    if (this.openPath) { this.inputChange.emit({ path: this.openPath, value: false }); }
  }
}

// packages/renderer-react/src/components/CcAlert.tsx
import type { AlertComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

export interface CcAlertProps {
  component: AlertComponent;
  dataModel: DataModel;
  onInput: (path: string, value: unknown) => void;
}

export function CcAlert({ component, dataModel, onInput }: CcAlertProps) {
  const variant = component.variant ?? 'info';
  const showIcon = component.showIcon ?? true;
  const dismissible = component.dismissible ?? false;

  const getMessage = (): string => {
    if (component.messagePath) {
      const value = getByPointer(dataModel, component.messagePath);
      return String(value ?? '');
    }
    return component.message ?? '';
  };

  const isOpen = (): boolean => {
    if (component.openPath) {
      return Boolean(getByPointer(dataModel, component.openPath));
    }
    return true;
  };

  const handleDismiss = () => {
    if (component.openPath) {
      onInput(component.openPath, false);
    }
  };

  if (!isOpen()) return null;

  const variantStyles: Record<string, { bg: string; border: string; text: string }> = {
    info: { bg: 'var(--cc-alert-info-bg, #dbeafe)', border: 'var(--cc-alert-info-border, #93c5fd)', text: 'var(--cc-alert-info-text, #1e40af)' },
    success: { bg: 'var(--cc-alert-success-bg, #d1fae5)', border: 'var(--cc-alert-success-border, #6ee7b7)', text: 'var(--cc-alert-success-text, #065f46)' },
    warning: { bg: 'var(--cc-alert-warning-bg, #fef3c7)', border: 'var(--cc-alert-warning-border, #fcd34d)', text: 'var(--cc-alert-warning-text, #92400e)' },
    error: { bg: 'var(--cc-alert-error-bg, #fee2e2)', border: 'var(--cc-alert-error-border, #fca5a5)', text: 'var(--cc-alert-error-text, #991b1b)' },
  };

  const icons: Record<string, string> = {
    info: 'info',
    success: 'check_circle',
    warning: 'warning',
    error: 'error',
  };

  const styles = variantStyles[variant] ?? variantStyles.info;
  const message = getMessage();

  return (
    <div
      className={`cc-alert cc-alert-${variant}`}
      role="alert"
      style={{
        display: 'flex',
        gap: 12,
        padding: '12px 16px',
        borderRadius: 8,
        border: `1px solid ${styles.border}`,
        backgroundColor: styles.bg,
        color: styles.text,
      }}
    >
      {showIcon && (
        <span className="cc-alert-icon material-icons" style={{ fontSize: '1.25rem', flexShrink: 0 }}>
          {icons[variant]}
        </span>
      )}
      <div style={{ flex: 1, minWidth: 0 }}>
        {component.title && (
          <p style={{ fontWeight: 600, fontSize: '0.875rem', margin: '0 0 4px' }}>
            {component.title}
          </p>
        )}
        <p style={{ fontSize: '0.875rem', margin: 0, lineHeight: 1.5 }}>
          {message}
        </p>
      </div>
      {dismissible && (
        <button
          className="cc-alert-close"
          onClick={handleDismiss}
          aria-label="Dismiss"
          style={{
            background: 'transparent',
            border: 'none',
            padding: 4,
            cursor: 'pointer',
            color: 'inherit',
            opacity: 0.6,
            fontSize: '1.25rem',
            lineHeight: 1,
            flexShrink: 0,
          }}
        >
          ×
        </button>
      )}
    </div>
  );
}
