// packages/renderer-angular/src/lib/cc-surface.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnChanges,
  SimpleChanges,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  Surface,
  DataModel,
  ComponentDefinition,
  UserActionMessage,
  Action,
  AgentToClientMessage,
} from './types';
import { setByPointer } from './utils/json-pointer';
import { CcComponentRendererComponent } from './components/cc-component-renderer.component';

/**
 * Main surface component for rendering ClaudeCanvas UIs
 * Can be used as a standalone component or as a custom element via Angular Elements
 */
@Component({
  selector: 'cc-surface',
  standalone: true,
  imports: [
    CommonModule,
    CcComponentRendererComponent,
  ],
  template: `
    <div class="cc-surface">
      @if (surface?.title) {
        <h2 class="cc-surface-title">{{ surface.title }}</h2>
      }
      @for (component of surface?.components || []; track $index) {
        <cc-component-renderer
          [component]="component"
          [dataModel]="dataModel"
          (inputChange)="handleInput($event.path, $event.value)"
          (action)="handleAction($event)">
        </cc-component-renderer>
      }
    </div>
  `,
  styles: [`
    .cc-surface {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
    }
    .cc-surface-title {
      font-size: 1.5rem;
      font-weight: 600;
      margin-bottom: 1rem;
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcSurfaceComponent implements OnChanges {
  @Input() surface: Surface | null = null;
  @Input() initialDataModel: DataModel = {};

  @Output() action = new EventEmitter<UserActionMessage>();
  @Output() dataModelChange = new EventEmitter<DataModel>();

  dataModel: DataModel = {};

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['initialDataModel']) {
      this.dataModel = { ...this.initialDataModel };
    }
  }

  /**
   * Process messages from the agent
   * This method can be called from outside when using as a custom element
   */
  processMessages(messages: AgentToClientMessage[]): void {
    for (const message of messages) {
      this.processMessage(message);
    }
    this.cdr.markForCheck();
  }

  /**
   * Process a single message from the agent
   */
  processMessage(message: AgentToClientMessage): void {
    switch (message.type) {
      case 'surfaceUpdate':
        this.surface = message.surface;
        break;
      case 'dataModelUpdate':
        this.dataModel = setByPointer(this.dataModel, message.path, message.data);
        this.dataModelChange.emit(this.dataModel);
        break;
      case 'deleteSurface':
        if (this.surface?.id === message.surfaceId) {
          this.surface = null;
        }
        break;
    }
    this.cdr.markForCheck();
  }

  handleInput(path: string, value: unknown): void {
    this.dataModel = setByPointer(this.dataModel, path, value);
    this.dataModelChange.emit(this.dataModel);
    this.cdr.markForCheck();
  }

  handleAction(actionData: Action): void {
    if (!this.surface) return;

    // Handle update/updateData action locally
    if ((actionData.type === 'updateData' || actionData.type === 'update') && actionData.path) {
      this.handleInput(actionData.path, actionData.value);
      return;
    }

    const message: UserActionMessage = {
      type: 'userAction',
      surfaceId: this.surface.id,
      action: actionData,
      dataModel: this.dataModel,
    };

    this.action.emit(message);
  }
}

// packages/renderer-lit/src/cc-surface.ts
import { LitElement, html, css, TemplateResult, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type {
  Surface,
  Component,
  DataModel,
  AgentToClientMessage,
  UserActionMessage,
  Action,
} from '@claude-canvas/core';
import { setByPointer, getByPointer, generateId } from '@claude-canvas/core';

// Import all components
import './components/index.js';

@customElement('cc-surface')
export class CcSurface extends LitElement {
  static styles = css`
    :host {
      display: block;
      font-family: var(--cc-font, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif);
      color: var(--cc-text, #333);
    }

    .surface {
      padding: 1rem;
    }

    .surface-title {
      font-size: 1.25rem;
      font-weight: 600;
      margin: 0 0 1rem 0;
    }
  `;

  @property({ type: Object })
  surface: Surface | null = null;

  @state()
  private dataModel: DataModel = {};

  /**
   * Process a message from the agent
   */
  processMessage(message: AgentToClientMessage): void {
    switch (message.type) {
      case 'surfaceUpdate':
        this.surface = message.surface;
        break;
      case 'dataModelUpdate':
        this.dataModel = setByPointer(this.dataModel, message.path, message.data);
        break;
      case 'deleteSurface':
        if (this.surface?.id === message.surfaceId) {
          this.surface = null;
        }
        break;
    }
  }

  /**
   * Process multiple messages from the agent
   */
  processMessages(messages: AgentToClientMessage[]): void {
    for (const message of messages) {
      this.processMessage(message);
    }
  }

  /**
   * Update the data model directly
   */
  updateDataModel(path: string, value: unknown): void {
    this.dataModel = setByPointer(this.dataModel, path, value);
  }

  private handleAction(e: CustomEvent<{ action: Action; dataModel: DataModel }>) {
    const { action } = e.detail;

    const userAction: UserActionMessage = {
      type: 'userAction',
      surfaceId: this.surface?.id ?? '',
      action,
      dataModel: this.dataModel,
    };

    this.dispatchEvent(new CustomEvent('cc-user-action', {
      bubbles: true,
      composed: true,
      detail: userAction,
    }));
  }

  private handleInput(e: CustomEvent<{ path: string; value: unknown }>) {
    const { path, value } = e.detail;
    this.dataModel = setByPointer(this.dataModel, path, value);
  }

  private isVisible(component: Component): boolean {
    if (!component.visibleIf) return true;
    const value = getByPointer(this.dataModel, component.visibleIf);
    return Boolean(value);
  }

  private renderComponent(component: Component): TemplateResult | typeof nothing {
    if (!this.isVisible(component)) return nothing;

    const id = component.id ?? generateId();

    switch (component.component) {
      case 'Text':
        return html`<cc-text .component=${component} .dataModel=${this.dataModel}></cc-text>`;

      case 'Button':
        return html`<cc-button .component=${component} .dataModel=${this.dataModel}></cc-button>`;

      case 'TextField':
        return html`<cc-text-field .component=${component} .dataModel=${this.dataModel}></cc-text-field>`;

      case 'Row':
        return html`
          <cc-row .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-row>
        `;

      case 'Column':
        return html`
          <cc-column .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-column>
        `;

      case 'Card':
        return html`
          <cc-card .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-card>
        `;

      case 'Divider':
        return html`<hr style=${component.vertical ? 'width: 1px; height: 100%; margin: 0 0.5rem;' : ''} />`;

      default:
        console.warn(`Unknown component type: ${(component as Component).component}`);
        return nothing;
    }
  }

  render() {
    if (!this.surface) {
      return html`<div class="surface"><slot></slot></div>`;
    }

    return html`
      <div class="surface" @cc-action=${this.handleAction} @cc-input=${this.handleInput}>
        ${this.surface.title ? html`<h2 class="surface-title">${this.surface.title}</h2>` : nothing}
        ${this.surface.components.map(component => this.renderComponent(component))}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-surface': CcSurface;
  }
}
