// packages/renderer-lit/src/cc-surface.ts
import { LitElement, html, css, TemplateResult, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type {
  Surface,
  Component,
  DataModel,
  AgentToClientMessage,
  UserActionMessage,
  Action,
  VisibilityCondition,
  ListComponent,
} from '@claude-canvas/core';
import { setByPointer, getByPointer, generateId, interpolatePath, evaluateExpression } from '@claude-canvas/core';

// Import all components
import './components/index.js';

@customElement('cc-surface')
export class CcSurface extends LitElement {
  static styles = css`
    :host {
      display: block;
      font-family: var(--cc-font, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif);
      color: var(--cc-text, #333);
    }

    .surface {
      padding: 1rem;
    }

    .surface-title {
      font-size: 1.25rem;
      font-weight: 600;
      margin: 0 0 1rem 0;
    }
  `;

  @property({ type: Object })
  surface: Surface | null = null;

  @state()
  private dataModel: DataModel = {};

  /**
   * Process a message from the agent
   */
  processMessage(message: AgentToClientMessage): void {
    switch (message.type) {
      case 'surfaceUpdate':
        this.surface = message.surface;
        break;
      case 'dataModelUpdate':
        this.dataModel = setByPointer(this.dataModel, message.path, message.data);
        break;
      case 'deleteSurface':
        if (this.surface?.id === message.surfaceId) {
          this.surface = null;
        }
        break;
    }
  }

  /**
   * Process multiple messages from the agent
   */
  processMessages(messages: AgentToClientMessage[]): void {
    for (const message of messages) {
      this.processMessage(message);
    }
  }

  /**
   * Update the data model directly
   */
  updateDataModel(path: string, value: unknown): void {
    this.dataModel = setByPointer(this.dataModel, path, value);
  }

  private handleAction(e: CustomEvent<{ action: Action; dataModel: DataModel }>) {
    const { action } = e.detail;

    // Handle update/updateData action locally - used for modal open/close, etc.
    if ((action.type === 'updateData' || action.type === 'update') && action.path !== undefined) {
      this.dataModel = setByPointer(this.dataModel, action.path, action.value);
      return;
    }

    const userAction: UserActionMessage = {
      type: 'userAction',
      surfaceId: this.surface?.id ?? '',
      action,
      dataModel: this.dataModel,
    };

    this.dispatchEvent(new CustomEvent('cc-user-action', {
      bubbles: true,
      composed: true,
      detail: userAction,
    }));
  }

  private handleInput(e: CustomEvent<{ path: string; value: unknown }>) {
    const { path, value } = e.detail;
    this.dataModel = setByPointer(this.dataModel, path, value);
  }

  private isVisible(component: Component): boolean {
    if (!component.visibleIf) return true;

    // Simple string path - truthy check
    if (typeof component.visibleIf === 'string') {
      const value = getByPointer(this.dataModel, component.visibleIf);
      return Boolean(value);
    }

    // Object syntax with comparison operators
    const condition = component.visibleIf as VisibilityCondition;
    let value = getByPointer(this.dataModel, condition.path);

    // Apply computed expression if specified
    if (condition.expr) {
      value = evaluateExpression(condition.expr, value);
    }

    if (condition.eq !== undefined) return value === condition.eq;
    if (condition.neq !== undefined) return value !== condition.neq;
    if (condition.gt !== undefined) return typeof value === 'number' && value > condition.gt;
    if (condition.gte !== undefined) return typeof value === 'number' && value >= condition.gte;
    if (condition.lt !== undefined) return typeof value === 'number' && value < condition.lt;
    if (condition.lte !== undefined) return typeof value === 'number' && value <= condition.lte;

    // Default to truthy check if no operator specified
    return Boolean(value);
  }

  /**
   * Render a List component by iterating over data and rendering template for each item
   */
  private renderList(component: ListComponent): TemplateResult | typeof nothing {
    const items = getByPointer(this.dataModel, component.itemsPath) as unknown[];

    if (!Array.isArray(items) || items.length === 0) {
      if (component.emptyMessage) {
        return html`<div class="list-empty">${component.emptyMessage}</div>`;
      }
      return nothing;
    }

    const gap = component.gap ?? 0;
    const containerStyle = gap ? `display: flex; flex-direction: column; gap: ${gap}px;` : '';

    return html`
      <div style=${containerStyle}>
        ${items.map((item, index) => {
          // Create a scoped data model with /item and /index available
          const scopedDataModel = {
            ...this.dataModel,
            item,
            index,
          };
          // Compute alternate background style
          const altBgStyle = component.alternateBackground && index % 2 === 1
            ? 'background-color: rgba(255,255,255,0.03);'
            : '';
          return html`<div style=${altBgStyle}>${this.renderComponentWithDataModel(component.itemTemplate, scopedDataModel, item, index)}</div>`;
        })}
      </div>
    `;
  }

  /**
   * Render a component with a custom data model (used for List iteration)
   * Supports path interpolation for {item.field} patterns
   */
  private renderComponentWithDataModel(
    component: Component,
    dataModel: DataModel,
    item?: unknown,
    index?: number
  ): TemplateResult | typeof nothing {
    if (!this.isVisibleWithDataModel(component, dataModel)) return nothing;

    // Helper to interpolate paths if item context is available
    const interpolate = (path: string): string => {
      if (item !== undefined && index !== undefined && path.includes('{')) {
        return interpolatePath(path, item, index);
      }
      return path;
    };

    switch (component.component) {
      case 'Text':
        return html`<cc-text .component=${component} .dataModel=${dataModel}></cc-text>`;
      case 'Button':
        return html`<cc-button .component=${component} .dataModel=${dataModel}></cc-button>`;
      case 'Image':
        return html`<cc-image .component=${component} .dataModel=${dataModel}></cc-image>`;
      case 'Badge':
        return html`<cc-badge .component=${component} .dataModel=${dataModel}></cc-badge>`;
      case 'Avatar':
        return html`<cc-avatar .component=${component} .dataModel=${dataModel}></cc-avatar>`;
      case 'Checkbox': {
        // Support path interpolation for checkbox valuePath
        const checkboxComp = { ...component };
        if ('valuePath' in checkboxComp && typeof checkboxComp.valuePath === 'string') {
          (checkboxComp as Record<string, unknown>).valuePath = interpolate(checkboxComp.valuePath as string);
        }
        return html`<cc-checkbox .component=${checkboxComp} .dataModel=${dataModel}></cc-checkbox>`;
      }
      case 'Row':
        return html`
          <cc-row .component=${component} .dataModel=${dataModel}>
            ${component.children.map(child => this.renderComponentWithDataModel(child, dataModel, item, index))}
          </cc-row>
        `;
      case 'Column':
        return html`
          <cc-column .component=${component} .dataModel=${dataModel}>
            ${component.children.map(child => this.renderComponentWithDataModel(child, dataModel, item, index))}
          </cc-column>
        `;
      case 'Card':
        return html`
          <cc-card .component=${component} .dataModel=${dataModel}>
            ${component.children.map(child => this.renderComponentWithDataModel(child, dataModel, item, index))}
          </cc-card>
        `;
      default:
        // Fall back to regular rendering for other components
        return this.renderComponent(component);
    }
  }

  private isVisibleWithDataModel(component: Component, dataModel: DataModel): boolean {
    if (!component.visibleIf) return true;

    if (typeof component.visibleIf === 'string') {
      const value = getByPointer(dataModel, component.visibleIf);
      return Boolean(value);
    }

    const condition = component.visibleIf as VisibilityCondition;
    let value = getByPointer(dataModel, condition.path);

    // Apply computed expression if specified
    if (condition.expr) {
      value = evaluateExpression(condition.expr, value);
    }

    if (condition.eq !== undefined) return value === condition.eq;
    if (condition.neq !== undefined) return value !== condition.neq;
    if (condition.gt !== undefined) return typeof value === 'number' && value > condition.gt;
    if (condition.gte !== undefined) return typeof value === 'number' && value >= condition.gte;
    if (condition.lt !== undefined) return typeof value === 'number' && value < condition.lt;
    if (condition.lte !== undefined) return typeof value === 'number' && value <= condition.lte;

    return Boolean(value);
  }

  private renderComponent(component: Component): TemplateResult | typeof nothing {
    if (!this.isVisible(component)) return nothing;

    const id = component.id ?? generateId();

    switch (component.component) {
      case 'Text':
        return html`<cc-text .component=${component} .dataModel=${this.dataModel}></cc-text>`;

      case 'Button':
        return html`<cc-button .component=${component} .dataModel=${this.dataModel}></cc-button>`;

      case 'TextField':
        return html`<cc-text-field .component=${component} .dataModel=${this.dataModel}></cc-text-field>`;

      case 'Checkbox':
        return html`<cc-checkbox .component=${component} .dataModel=${this.dataModel}></cc-checkbox>`;

      case 'Select':
        return html`<cc-select .component=${component} .dataModel=${this.dataModel}></cc-select>`;

      case 'Slider':
        return html`<cc-slider .component=${component} .dataModel=${this.dataModel}></cc-slider>`;

      case 'DateTimeInput':
        return html`<cc-datetime-input .component=${component} .dataModel=${this.dataModel}></cc-datetime-input>`;

      case 'Video':
        return html`<cc-video .component=${component} .dataModel=${this.dataModel}></cc-video>`;

      case 'AudioPlayer':
        return html`<cc-audio-player .component=${component} .dataModel=${this.dataModel}></cc-audio-player>`;

      case 'MultipleChoice':
        return html`<cc-multiple-choice .component=${component} .dataModel=${this.dataModel}></cc-multiple-choice>`;

      case 'Chart':
        return html`<cc-chart .component=${component} .dataModel=${this.dataModel}></cc-chart>`;

      case 'DataTable':
        return html`<cc-data-table .component=${component} .dataModel=${this.dataModel}></cc-data-table>`;

      case 'RichTextEditor':
        return html`<cc-rich-text-editor .component=${component} .dataModel=${this.dataModel}></cc-rich-text-editor>`;

      case 'Image':
        return html`<cc-image .component=${component} .dataModel=${this.dataModel}></cc-image>`;

      case 'Icon':
        return html`<cc-icon .component=${component} .dataModel=${this.dataModel}></cc-icon>`;

      case 'Row':
        return html`
          <cc-row .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-row>
        `;

      case 'Column':
        return html`
          <cc-column .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-column>
        `;

      case 'Card':
        return html`
          <cc-card .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-card>
        `;

      case 'Divider':
        return html`<hr style=${component.vertical ? 'width: 1px; height: 100%; margin: 0 0.5rem;' : ''} />`;

      case 'Modal':
        return html`
          <cc-modal .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-modal>
        `;

      case 'Tabs': {
        const activeTabValue = getByPointer(this.dataModel, component.valuePath) as string | undefined;
        const activeTab = activeTabValue ?? component.tabs[0]?.value;
        const activeTabData = component.tabs.find(tab => tab.value === activeTab);
        return html`
          <cc-tabs .component=${component} .dataModel=${this.dataModel}>
            ${activeTabData ? activeTabData.children.map(child => this.renderComponent(child)) : nothing}
          </cc-tabs>
        `;
      }

      case 'Progress':
        return html`<cc-progress .component=${component} .dataModel=${this.dataModel}></cc-progress>`;

      case 'Badge':
        return html`<cc-badge .component=${component} .dataModel=${this.dataModel}></cc-badge>`;

      case 'Avatar':
        return html`<cc-avatar .component=${component} .dataModel=${this.dataModel}></cc-avatar>`;

      case 'Toast':
        return html`<cc-toast .component=${component} .dataModel=${this.dataModel}></cc-toast>`;

      case 'Accordion':
        return html`
          <cc-accordion .component=${component} .dataModel=${this.dataModel}>
            ${component.items.map(item =>
              item.children.map(child => this.renderComponent(child))
            )}
          </cc-accordion>
        `;

      case 'Skeleton':
        return html`<cc-skeleton .component=${component} .dataModel=${this.dataModel}></cc-skeleton>`;

      case 'Alert':
        return html`<cc-alert .component=${component} .dataModel=${this.dataModel}></cc-alert>`;

      case 'Tooltip':
        return html`
          <cc-tooltip .component=${component} .dataModel=${this.dataModel}>
            ${component.children.map(child => this.renderComponent(child))}
          </cc-tooltip>
        `;

      case 'List':
        return this.renderList(component as ListComponent);

      default:
        console.warn(`Unknown component type: ${(component as Component).component}`);
        return nothing;
    }
  }

  render() {
    if (!this.surface) {
      return html`<div class="surface"><slot></slot></div>`;
    }

    return html`
      <div class="surface" @cc-action=${this.handleAction} @cc-input=${this.handleInput}>
        ${this.surface.title ? html`<h2 class="surface-title">${this.surface.title}</h2>` : nothing}
        ${this.surface.components.map(component => this.renderComponent(component))}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-surface': CcSurface;
  }
}

// packages/renderer-react/src/CcSurface.tsx
import React, { useState, useCallback, useEffect } from 'react';
import type {
  Surface,
  Component,
  DataModel,
  AgentToClientMessage,
  UserActionMessage,
  Action,
  VisibilityCondition,
  ListComponent,
} from '@claude-canvas/core';
import { setByPointer, getByPointer, generateId, interpolatePath, evaluateExpression } from '@claude-canvas/core';

import { CcText } from './components/CcText.js';
import { CcButton } from './components/CcButton.js';
import { CcTextField } from './components/CcTextField.js';
import { CcCheckbox } from './components/CcCheckbox.js';
import { CcSelect } from './components/CcSelect.js';
import { CcSlider } from './components/CcSlider.js';
import { CcDateTimeInput } from './components/CcDateTimeInput.js';
import { CcVideo } from './components/CcVideo.js';
import { CcAudioPlayer } from './components/CcAudioPlayer.js';
import { CcMultipleChoice } from './components/CcMultipleChoice.js';
import { CcChart } from './components/CcChart.js';
import { CcDataTable } from './components/CcDataTable.js';
import { CcRichTextEditor } from './components/CcRichTextEditor.js';
import { CcImage } from './components/CcImage.js';
import { CcIcon } from './components/CcIcon.js';
import { CcRow } from './components/CcRow.js';
import { CcColumn } from './components/CcColumn.js';
import { CcCard } from './components/CcCard.js';
import { CcDivider } from './components/CcDivider.js';
import { CcModal } from './components/CcModal.js';
import { CcTabs } from './components/CcTabs.js';
import { CcProgress } from './components/CcProgress.js';
import { CcBadge } from './components/CcBadge.js';
import { CcAvatar } from './components/CcAvatar.js';
import { CcToast } from './components/CcToast.js';
import { CcAccordion } from './components/CcAccordion.js';
import { CcSkeleton } from './components/CcSkeleton.js';
import { CcAlert } from './components/CcAlert.js';
import { CcTooltip } from './components/CcTooltip.js';

export interface CcSurfaceProps {
  /** The surface definition to render */
  surface?: Surface | null;
  /** Initial data model state */
  initialDataModel?: DataModel;
  /** Called when a user performs an action (button click, etc.) */
  onAction?: (message: UserActionMessage) => void;
  /** Called when the data model changes (input changes) */
  onDataModelChange?: (dataModel: DataModel) => void;
  /** Children to render when no surface is provided */
  children?: React.ReactNode;
}

export function CcSurface({
  surface,
  initialDataModel = {},
  onAction,
  onDataModelChange,
  children,
}: CcSurfaceProps) {
  const [dataModel, setDataModel] = useState<DataModel>(initialDataModel);

  // Update data model when initial changes
  useEffect(() => {
    setDataModel(initialDataModel);
  }, [initialDataModel]);

  const handleInput = useCallback((path: string, value: unknown) => {
    setDataModel(prev => {
      const next = setByPointer(prev, path, value);
      onDataModelChange?.(next);
      return next;
    });
  }, [onDataModelChange]);

  const handleAction = useCallback((action: Action) => {
    if (!surface) return;

    // Handle update/updateData action locally - used for modal open/close, etc.
    if ((action.type === 'updateData' || action.type === 'update') && action.path !== undefined) {
      handleInput(action.path, action.value);
      return;
    }

    const message: UserActionMessage = {
      type: 'userAction',
      surfaceId: surface.id,
      action,
      dataModel,
    };

    onAction?.(message);
  }, [surface, dataModel, onAction, handleInput]);

  const isVisible = (component: Component): boolean => {
    if (!component.visibleIf) return true;

    // Simple string path - truthy check
    if (typeof component.visibleIf === 'string') {
      const value = getByPointer(dataModel, component.visibleIf);
      return Boolean(value);
    }

    // Object syntax with comparison operators
    const condition = component.visibleIf as VisibilityCondition;
    let value = getByPointer(dataModel, condition.path);

    // Apply computed expression if specified
    if (condition.expr) {
      value = evaluateExpression(condition.expr, value);
    }

    if (condition.eq !== undefined) return value === condition.eq;
    if (condition.neq !== undefined) return value !== condition.neq;
    if (condition.gt !== undefined) return typeof value === 'number' && value > condition.gt;
    if (condition.gte !== undefined) return typeof value === 'number' && value >= condition.gte;
    if (condition.lt !== undefined) return typeof value === 'number' && value < condition.lt;
    if (condition.lte !== undefined) return typeof value === 'number' && value <= condition.lte;

    // Default to truthy check if no operator specified
    return Boolean(value);
  };

  // Check visibility with a custom data model (used for List iteration)
  const isVisibleWithDataModel = (component: Component, dm: DataModel): boolean => {
    if (!component.visibleIf) return true;

    if (typeof component.visibleIf === 'string') {
      const value = getByPointer(dm, component.visibleIf);
      return Boolean(value);
    }

    const condition = component.visibleIf as VisibilityCondition;
    let value = getByPointer(dm, condition.path);

    // Apply computed expression if specified
    if (condition.expr) {
      value = evaluateExpression(condition.expr, value);
    }

    if (condition.eq !== undefined) return value === condition.eq;
    if (condition.neq !== undefined) return value !== condition.neq;
    if (condition.gt !== undefined) return typeof value === 'number' && value > condition.gt;
    if (condition.gte !== undefined) return typeof value === 'number' && value >= condition.gte;
    if (condition.lt !== undefined) return typeof value === 'number' && value < condition.lt;
    if (condition.lte !== undefined) return typeof value === 'number' && value <= condition.lte;

    return Boolean(value);
  };

  // Render a component with a scoped data model (used for List iteration)
  // Supports path interpolation for {item.field} patterns
  const renderComponentWithDataModel = (
    component: Component,
    dm: DataModel,
    item?: unknown,
    index?: number,
    key?: string | number
  ): React.ReactNode => {
    if (!isVisibleWithDataModel(component, dm)) return null;

    const id = component.id ?? generateId();
    const componentKey = key ?? id;

    // Helper to interpolate paths if item context is available
    const interpolate = (path: string): string => {
      if (item !== undefined && index !== undefined && path.includes('{')) {
        return interpolatePath(path, item, index);
      }
      return path;
    };

    switch (component.component) {
      case 'Text':
        return <CcText key={componentKey} component={component} dataModel={dm} />;
      case 'Button':
        return <CcButton key={componentKey} component={component} dataModel={dm} onAction={handleAction} />;
      case 'Image':
        return <CcImage key={componentKey} component={component} dataModel={dm} />;
      case 'Badge':
        return <CcBadge key={componentKey} component={component} dataModel={dm} />;
      case 'Avatar':
        return <CcAvatar key={componentKey} component={component} dataModel={dm} />;
      case 'Checkbox': {
        // Support path interpolation for checkbox valuePath
        const checkboxComp = { ...component };
        if ('valuePath' in checkboxComp && typeof checkboxComp.valuePath === 'string') {
          (checkboxComp as Record<string, unknown>).valuePath = interpolate(checkboxComp.valuePath as string);
        }
        return (
          <CcCheckbox
            key={componentKey}
            component={checkboxComp}
            dataModel={dm}
            onInput={handleInput}
          />
        );
      }
      case 'Row':
        return (
          <CcRow key={componentKey} component={component} dataModel={dm}>
            {component.children.map((child, i) => renderComponentWithDataModel(child, dm, item, index, i))}
          </CcRow>
        );
      case 'Column':
        return (
          <CcColumn key={componentKey} component={component} dataModel={dm}>
            {component.children.map((child, i) => renderComponentWithDataModel(child, dm, item, index, i))}
          </CcColumn>
        );
      case 'Card':
        return (
          <CcCard key={componentKey} component={component} dataModel={dm}>
            {component.children.map((child, i) => renderComponentWithDataModel(child, dm, item, index, i))}
          </CcCard>
        );
      default:
        // Fall back to regular render for unsupported components in list context
        return renderComponent(component, componentKey);
    }
  };

  // Render a List component by iterating over array data
  const renderList = (component: ListComponent, key?: string | number): React.ReactNode => {
    const items = getByPointer(dataModel, component.itemsPath) as unknown[];

    if (!Array.isArray(items) || items.length === 0) {
      if (component.emptyMessage) {
        return <div key={key} className="cc-list-empty">{component.emptyMessage}</div>;
      }
      return null;
    }

    const gap = component.gap ?? 0;
    const containerStyle: React.CSSProperties = gap
      ? { display: 'flex', flexDirection: 'column', gap: `${gap}px` }
      : {};

    return (
      <div key={key} style={containerStyle}>
        {items.map((item, index) => {
          // Create a scoped data model with /item and /index available
          const scopedDataModel = {
            ...dataModel,
            item,
            index,
          };
          // Compute alternate background style
          const altBgStyle: React.CSSProperties = component.alternateBackground && index % 2 === 1
            ? { backgroundColor: 'rgba(255,255,255,0.03)' }
            : {};
          return (
            <div key={index} style={altBgStyle}>
              {renderComponentWithDataModel(component.itemTemplate, scopedDataModel, item, index, index)}
            </div>
          );
        })}
      </div>
    );
  };

  const renderComponent = (component: Component, key?: string | number): React.ReactNode => {
    if (!isVisible(component)) return null;

    const id = component.id ?? generateId();
    const componentKey = key ?? id;

    switch (component.component) {
      case 'Text':
        return <CcText key={componentKey} component={component} dataModel={dataModel} />;

      case 'Button':
        return (
          <CcButton
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onAction={handleAction}
          />
        );

      case 'TextField':
        return (
          <CcTextField
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'Checkbox':
        return (
          <CcCheckbox
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'Select':
        return (
          <CcSelect
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'Slider':
        return (
          <CcSlider
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'DateTimeInput':
        return (
          <CcDateTimeInput
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'Video':
        return <CcVideo key={componentKey} component={component} dataModel={dataModel} />;

      case 'AudioPlayer':
        return <CcAudioPlayer key={componentKey} component={component} dataModel={dataModel} />;

      case 'MultipleChoice':
        return (
          <CcMultipleChoice
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'Chart':
        return <CcChart key={componentKey} component={component} dataModel={dataModel} />;

      case 'DataTable':
        return (
          <CcDataTable
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'RichTextEditor':
        return (
          <CcRichTextEditor
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'Image':
        return <CcImage key={componentKey} component={component} dataModel={dataModel} />;

      case 'Icon':
        return <CcIcon key={componentKey} component={component} dataModel={dataModel} />;

      case 'Row':
        return (
          <CcRow key={componentKey} component={component} dataModel={dataModel}>
            {component.children.map((child, i) => renderComponent(child, i))}
          </CcRow>
        );

      case 'Column':
        return (
          <CcColumn key={componentKey} component={component} dataModel={dataModel}>
            {component.children.map((child, i) => renderComponent(child, i))}
          </CcColumn>
        );

      case 'Card':
        return (
          <CcCard key={componentKey} component={component} dataModel={dataModel}>
            {component.children.map((child, i) => renderComponent(child, i))}
          </CcCard>
        );

      case 'Divider':
        return <CcDivider key={componentKey} component={component} dataModel={dataModel} />;

      case 'Modal':
        return (
          <CcModal
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          >
            {component.children.map((child, i) => renderComponent(child, i))}
          </CcModal>
        );

      case 'Tabs':
        return (
          <CcTabs
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
            renderChildren={(children) => children.map((child, i) => renderComponent(child, i))}
          />
        );

      case 'Progress':
        return <CcProgress key={componentKey} component={component} dataModel={dataModel} />;

      case 'Badge':
        return <CcBadge key={componentKey} component={component} dataModel={dataModel} />;

      case 'Avatar':
        return <CcAvatar key={componentKey} component={component} dataModel={dataModel} />;

      case 'Toast':
        return (
          <CcToast
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
            onAction={handleAction}
          />
        );

      case 'Accordion':
        return (
          <CcAccordion
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
            renderChildren={(children) => children.map((child, i) => renderComponent(child, i))}
          />
        );

      case 'Skeleton':
        return <CcSkeleton key={componentKey} component={component} dataModel={dataModel} />;

      case 'Alert':
        return (
          <CcAlert
            key={componentKey}
            component={component}
            dataModel={dataModel}
            onInput={handleInput}
          />
        );

      case 'Tooltip':
        return (
          <CcTooltip key={componentKey} component={component} dataModel={dataModel}>
            {component.children.map((child, i) => renderComponent(child, i))}
          </CcTooltip>
        );

      case 'List':
        return renderList(component as ListComponent, componentKey);

      default:
        console.warn(`Unknown component type: ${(component as Component).component}`);
        return null;
    }
  };

  if (!surface) {
    return <div className="cc-surface">{children}</div>;
  }

  return (
    <div className="cc-surface">
      {surface.title && <h2 className="cc-surface-title">{surface.title}</h2>}
      {surface.components.map((component, i) => renderComponent(component, i))}
    </div>
  );
}

/**
 * Hook to manage surface state with message processing
 */
export function useCcSurface(initialSurface?: Surface | null, initialDataModel?: DataModel) {
  const [surface, setSurface] = useState<Surface | null>(initialSurface ?? null);
  const [dataModel, setDataModel] = useState<DataModel>(initialDataModel ?? {});

  const processMessage = useCallback((message: AgentToClientMessage) => {
    switch (message.type) {
      case 'surfaceUpdate':
        setSurface(message.surface);
        break;
      case 'dataModelUpdate':
        setDataModel(prev => setByPointer(prev, message.path, message.data));
        break;
      case 'deleteSurface':
        setSurface(prev => (prev?.id === message.surfaceId ? null : prev));
        break;
    }
  }, []);

  const processMessages = useCallback((messages: AgentToClientMessage[]) => {
    for (const message of messages) {
      processMessage(message);
    }
  }, [processMessage]);

  const updateDataModel = useCallback((path: string, value: unknown) => {
    setDataModel(prev => setByPointer(prev, path, value));
  }, []);

  return {
    surface,
    dataModel,
    setSurface,
    setDataModel,
    processMessage,
    processMessages,
    updateDataModel,
  };
}
