// packages/renderer-lit/src/components/cc-badge.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { BadgeComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-badge')
export class CcBadge extends LitElement {
  static styles = css`
    :host {
      display: inline-block;
    }

    .badge {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      font-weight: 500;
      white-space: nowrap;
    }

    /* Sizes */
    .small {
      padding: 2px 6px;
      font-size: 0.625rem;
      border-radius: 4px;
    }

    .medium {
      padding: 4px 8px;
      font-size: 0.75rem;
      border-radius: 6px;
    }

    .large {
      padding: 6px 12px;
      font-size: 0.875rem;
      border-radius: 8px;
    }

    /* Pill shape */
    .pill.small { border-radius: 10px; }
    .pill.medium { border-radius: 12px; }
    .pill.large { border-radius: 16px; }

    /* Variants */
    .default {
      background: var(--cc-badge-default-bg, #e5e7eb);
      color: var(--cc-badge-default-text, #374151);
    }

    .success {
      background: var(--cc-badge-success-bg, #d1fae5);
      color: var(--cc-badge-success-text, #065f46);
    }

    .warning {
      background: var(--cc-badge-warning-bg, #fef3c7);
      color: var(--cc-badge-warning-text, #92400e);
    }

    .error {
      background: var(--cc-badge-error-bg, #fee2e2);
      color: var(--cc-badge-error-text, #991b1b);
    }

    .info {
      background: var(--cc-badge-info-bg, #dbeafe);
      color: var(--cc-badge-info-text, #1e40af);
    }

    /* Dot indicator */
    .dot {
      width: 8px;
      height: 8px;
      padding: 0;
      border-radius: 50%;
    }

    .dot.small { width: 6px; height: 6px; }
    .dot.large { width: 10px; height: 10px; }

    .icon {
      font-size: 1em;
    }
  `;

  @property({ type: Object })
  component!: BadgeComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getContent(): string {
    if (this.component.contentPath) {
      const value = getByPointer(this.dataModel, this.component.contentPath);
      return String(value ?? '');
    }
    return this.component.content ?? '';
  }

  render() {
    const content = this.getContent();
    const variant = this.component.variant ?? 'default';
    const size = this.component.size ?? 'medium';
    const pill = this.component.pill ?? false;
    const dot = this.component.dot ?? false;

    const customStyles: string[] = [];
    if (this.component.color) {
      customStyles.push(`background: ${this.component.color}`);
    }
    if (this.component.textColor) {
      customStyles.push(`color: ${this.component.textColor}`);
    }

    const classes = [
      'badge',
      variant,
      size,
      pill ? 'pill' : '',
      dot ? 'dot' : '',
    ].filter(Boolean).join(' ');

    return html`
      <span class="${classes}" style="${customStyles.join('; ')}">
        ${this.component.icon && !dot ? html`<span class="icon">${this.component.icon}</span>` : ''}
        ${!dot ? content : ''}
      </span>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-badge': CcBadge;
  }
}

// packages/renderer-angular/src/lib/components/cc-badge.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (dot) {
      <span class="cc-badge-dot" [class]="variantClass"></span>
    } @else {
      <span class="cc-badge" [class]="badgeClasses">
        @if (icon) { <span class="cc-badge-icon">{{ icon }}</span> }
        {{ content }}
      </span>
    }
  `,
  styles: [`
    .cc-badge {
      display: inline-flex; align-items: center; gap: 0.25rem;
      padding: 0.25rem 0.5rem; border-radius: 0.25rem; font-size: 0.75rem; font-weight: 500;
    }
    .cc-badge.pill { border-radius: 9999px; }
    .cc-badge-dot { width: 0.5rem; height: 0.5rem; border-radius: 50%; }
    .cc-badge-default { background: #f1f5f9; color: #475569; }
    .cc-badge-success { background: #dcfce7; color: #166534; }
    .cc-badge-warning { background: #fef3c7; color: #92400e; }
    .cc-badge-error { background: #fee2e2; color: #b91c1c; }
    .cc-badge-info { background: #dbeafe; color: #1e40af; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcBadgeComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};

  get content(): string {
    if (this.component['contentPath']) {
      const v = getByPointer(this.dataModel, this.component['contentPath'] as string);
      return v?.toString() ?? '';
    }
    return (this.component['content'] as string) ?? '';
  }
  get variant(): string { return (this.component['variant'] as string) ?? 'default'; }
  get pill(): boolean { return (this.component['pill'] as boolean) ?? false; }
  get dot(): boolean { return (this.component['dot'] as boolean) ?? false; }
  get icon(): string | undefined { return this.component['icon'] as string; }
  get variantClass(): string { return `cc-badge-${this.variant}`; }
  get badgeClasses(): string { return `${this.variantClass}${this.pill ? ' pill' : ''}`; }
}
