// packages/renderer-lit/src/components/cc-checkbox.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { CheckboxComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-checkbox')
export class CcCheckbox extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .checkbox-wrapper {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      cursor: pointer;
    }

    .checkbox-wrapper:has(input:disabled) {
      cursor: not-allowed;
      opacity: 0.6;
    }

    input[type="checkbox"] {
      width: 1.125rem;
      height: 1.125rem;
      margin: 0;
      cursor: pointer;
      accent-color: var(--cc-primary, #6366f1);
    }

    input[type="checkbox"]:disabled {
      cursor: not-allowed;
    }

    label {
      font-size: 0.9375rem;
      color: var(--cc-text, #333);
      cursor: pointer;
      user-select: none;
    }

    label.disabled {
      cursor: not-allowed;
    }
  `;

  @property({ type: Object })
  component!: CheckboxComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getValue(): boolean {
    const value = getByPointer(this.dataModel, this.component.valuePath);
    return Boolean(value);
  }

  private handleChange(e: Event) {
    const target = e.target as HTMLInputElement;
    const event = new CustomEvent('cc-input', {
      bubbles: true,
      composed: true,
      detail: {
        path: this.component.valuePath,
        value: target.checked,
      },
    });
    this.dispatchEvent(event);
  }

  render() {
    const checked = this.getValue();
    const id = `checkbox-${this.component.valuePath.replace(/\//g, '-')}`;

    return html`
      <div class="checkbox-wrapper">
        <input
          type="checkbox"
          id=${id}
          .checked=${checked}
          ?disabled=${this.component.disabled}
          @change=${this.handleChange}
        />
        ${this.component.label
          ? html`<label for=${id} class=${this.component.disabled ? 'disabled' : ''}>${this.component.label}</label>`
          : null
        }
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-checkbox': CcCheckbox;
  }
}

// packages/renderer-angular/src/lib/components/cc-checkbox.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-checkbox',
  standalone: true,
  imports: [CommonModule],
  template: `
    <label class="cc-checkbox" [class.disabled]="disabled">
      <input
        type="checkbox"
        [checked]="checked"
        [disabled]="disabled"
        (change)="onChange($event)"
      />
      <span class="cc-checkbox-label">{{ label }}</span>
    </label>
  `,
  styles: [`
    .cc-checkbox {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      cursor: pointer;
    }
    .cc-checkbox.disabled { opacity: 0.5; cursor: not-allowed; }
    .cc-checkbox input { width: 1rem; height: 1rem; cursor: inherit; }
    .cc-checkbox-label { font-size: 0.875rem; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcCheckboxComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();

  get valuePath(): string | undefined {
    return this.component['valuePath'] as string | undefined;
  }

  get checked(): boolean {
    if (this.valuePath) {
      const value = getByPointer(this.dataModel, this.valuePath);
      return value === true;
    }
    return false;
  }

  get label(): string {
    return (this.component['label'] as string) ?? '';
  }

  get disabled(): boolean {
    return (this.component['disabled'] as boolean) ?? false;
  }

  onChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    if (this.valuePath) {
      this.inputChange.emit({ path: this.valuePath, value: target.checked });
    }
  }
}
