// packages/renderer-lit/src/components/cc-data-table.ts
import { LitElement, html, css, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { DataTableComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-data-table')
export class CcDataTable extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .table-wrapper {
      background: var(--cc-surface, white);
      border: 1px solid var(--cc-border, #e5e7eb);
      border-radius: 0.5rem;
      overflow: hidden;
    }

    .table-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 0.75rem 1rem;
      border-bottom: 1px solid var(--cc-border, #e5e7eb);
      background: var(--cc-surface-dim, #f9fafb);
    }

    .search-input {
      padding: 0.5rem 0.75rem;
      border: 1px solid var(--cc-border, #d1d5db);
      border-radius: 0.375rem;
      font-size: 0.875rem;
      width: 200px;
    }

    .search-input:focus {
      outline: none;
      border-color: var(--cc-primary, #6366f1);
    }

    table {
      width: 100%;
      border-collapse: collapse;
    }

    thead {
      background: var(--cc-surface-dim, #f9fafb);
    }

    th {
      padding: 0.75rem 1rem;
      text-align: left;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--cc-text-secondary, #6b7280);
      border-bottom: 1px solid var(--cc-border, #e5e7eb);
    }

    th.sortable {
      cursor: pointer;
      user-select: none;
    }

    th.sortable:hover {
      color: var(--cc-text, #333);
    }

    .sort-icon {
      margin-left: 0.25rem;
      opacity: 0.5;
    }

    .sort-icon.active {
      opacity: 1;
      color: var(--cc-primary, #6366f1);
    }

    td {
      padding: 0.75rem 1rem;
      font-size: 0.875rem;
      color: var(--cc-text, #333);
      border-bottom: 1px solid var(--cc-border, #e5e7eb);
    }

    tr:hover td {
      background: var(--cc-surface-dim, #f9fafb);
    }

    tr.selected td {
      background: rgba(99, 102, 241, 0.1);
    }

    .checkbox-cell {
      width: 40px;
      text-align: center;
    }

    .checkbox-cell input {
      width: 1rem;
      height: 1rem;
      cursor: pointer;
      accent-color: var(--cc-primary, #6366f1);
    }

    .empty-state {
      padding: 3rem;
      text-align: center;
      color: var(--cc-text-secondary, #6b7280);
    }

    .pagination {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 0.75rem 1rem;
      border-top: 1px solid var(--cc-border, #e5e7eb);
      background: var(--cc-surface-dim, #f9fafb);
      font-size: 0.875rem;
      color: var(--cc-text-secondary, #6b7280);
    }

    .pagination-buttons {
      display: flex;
      gap: 0.5rem;
    }

    .pagination-btn {
      padding: 0.375rem 0.75rem;
      border: 1px solid var(--cc-border, #d1d5db);
      border-radius: 0.375rem;
      background: var(--cc-surface, white);
      font-size: 0.875rem;
      cursor: pointer;
      color: var(--cc-text, #333);
    }

    .pagination-btn:hover:not(:disabled) {
      background: var(--cc-surface-dim, #f3f4f6);
    }

    .pagination-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
  `;

  @property({ type: Object })
  component!: DataTableComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  @state()
  private currentPage = 0;

  @state()
  private sortColumn: string | null = null;

  @state()
  private sortDirection: 'asc' | 'desc' = 'asc';

  @state()
  private searchQuery = '';

  @state()
  private selectedRows: Set<number> = new Set();

  private getData(): Record<string, unknown>[] {
    const data = getByPointer(this.dataModel, this.component.dataPath);
    if (Array.isArray(data)) {
      return data as Record<string, unknown>[];
    }
    return [];
  }

  private getFilteredData(): Record<string, unknown>[] {
    let data = this.getData();

    // Filter by search
    if (this.searchQuery && this.component.searchable) {
      const query = this.searchQuery.toLowerCase();
      data = data.filter(row =>
        this.component.columns.some(col => {
          const value = row[col.key];
          return String(value).toLowerCase().includes(query);
        })
      );
    }

    // Sort
    if (this.sortColumn) {
      const col = this.sortColumn;
      const dir = this.sortDirection === 'asc' ? 1 : -1;
      data = [...data].sort((a, b) => {
        const aVal = a[col];
        const bVal = b[col];
        if (aVal === bVal) return 0;
        if (aVal == null) return 1;
        if (bVal == null) return -1;
        if (typeof aVal === 'number' && typeof bVal === 'number') {
          return (aVal - bVal) * dir;
        }
        return String(aVal).localeCompare(String(bVal)) * dir;
      });
    }

    return data;
  }

  private getPagedData(): Record<string, unknown>[] {
    const data = this.getFilteredData();
    if (!this.component.pagination) return data;

    const pageSize = this.component.pageSize || 10;
    const start = this.currentPage * pageSize;
    return data.slice(start, start + pageSize);
  }

  private handleSort(columnKey: string) {
    const column = this.component.columns.find(c => c.key === columnKey);
    if (!column?.sortable) return;

    if (this.sortColumn === columnKey) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = columnKey;
      this.sortDirection = 'asc';
    }
  }

  private handleSearch(e: Event) {
    this.searchQuery = (e.target as HTMLInputElement).value;
    this.currentPage = 0;
  }

  private handleRowSelect(index: number) {
    if (!this.component.selectable) return;

    const newSelected = new Set(this.selectedRows);
    if (newSelected.has(index)) {
      newSelected.delete(index);
    } else {
      newSelected.add(index);
    }
    this.selectedRows = newSelected;

    if (this.component.selectionPath) {
      const selectedData = this.getData().filter((_, i) => newSelected.has(i));
      const event = new CustomEvent('cc-input', {
        bubbles: true,
        composed: true,
        detail: {
          path: this.component.selectionPath,
          value: selectedData,
        },
      });
      this.dispatchEvent(event);
    }
  }

  private handleSelectAll(e: Event) {
    const checked = (e.target as HTMLInputElement).checked;
    const data = this.getData();

    if (checked) {
      this.selectedRows = new Set(data.map((_, i) => i));
    } else {
      this.selectedRows = new Set();
    }

    if (this.component.selectionPath) {
      const selectedData = checked ? data : [];
      const event = new CustomEvent('cc-input', {
        bubbles: true,
        composed: true,
        detail: {
          path: this.component.selectionPath,
          value: selectedData,
        },
      });
      this.dispatchEvent(event);
    }
  }

  render() {
    const allData = this.getFilteredData();
    const pagedData = this.getPagedData();
    const pageSize = this.component.pageSize || 10;
    const totalPages = Math.ceil(allData.length / pageSize);

    return html`
      <div class="table-wrapper">
        ${this.component.searchable ? html`
          <div class="table-header">
            <input
              type="text"
              class="search-input"
              placeholder="Search..."
              .value=${this.searchQuery}
              @input=${this.handleSearch}
            />
          </div>
        ` : nothing}

        ${pagedData.length === 0 ? html`
          <div class="empty-state">
            ${this.component.emptyMessage || 'No data available'}
          </div>
        ` : html`
          <table>
            <thead>
              <tr>
                ${this.component.selectable ? html`
                  <th class="checkbox-cell">
                    <input
                      type="checkbox"
                      .checked=${this.selectedRows.size === this.getData().length && this.getData().length > 0}
                      @change=${this.handleSelectAll}
                    />
                  </th>
                ` : nothing}
                ${this.component.columns.map(col => html`
                  <th
                    class=${col.sortable ? 'sortable' : ''}
                    style=${col.width ? `width: ${typeof col.width === 'number' ? col.width + 'px' : col.width}` : ''}
                    @click=${() => this.handleSort(col.key)}
                  >
                    ${col.label}
                    ${col.sortable ? html`
                      <span class="sort-icon ${this.sortColumn === col.key ? 'active' : ''}">
                        ${this.sortColumn === col.key ? (this.sortDirection === 'asc' ? '↑' : '↓') : '↕'}
                      </span>
                    ` : nothing}
                  </th>
                `)}
              </tr>
            </thead>
            <tbody>
              ${pagedData.map((row, i) => {
                const actualIndex = this.component.pagination ? this.currentPage * pageSize + i : i;
                return html`
                  <tr class=${this.selectedRows.has(actualIndex) ? 'selected' : ''}>
                    ${this.component.selectable ? html`
                      <td class="checkbox-cell">
                        <input
                          type="checkbox"
                          .checked=${this.selectedRows.has(actualIndex)}
                          @change=${() => this.handleRowSelect(actualIndex)}
                        />
                      </td>
                    ` : nothing}
                    ${this.component.columns.map(col => html`
                      <td>${row[col.key] ?? ''}</td>
                    `)}
                  </tr>
                `;
              })}
            </tbody>
          </table>
        `}

        ${this.component.pagination && allData.length > pageSize ? html`
          <div class="pagination">
            <span>
              Showing ${this.currentPage * pageSize + 1} - ${Math.min((this.currentPage + 1) * pageSize, allData.length)} of ${allData.length}
            </span>
            <div class="pagination-buttons">
              <button
                class="pagination-btn"
                ?disabled=${this.currentPage === 0}
                @click=${() => this.currentPage = 0}
              >
                First
              </button>
              <button
                class="pagination-btn"
                ?disabled=${this.currentPage === 0}
                @click=${() => this.currentPage--}
              >
                Prev
              </button>
              <button
                class="pagination-btn"
                ?disabled=${this.currentPage >= totalPages - 1}
                @click=${() => this.currentPage++}
              >
                Next
              </button>
              <button
                class="pagination-btn"
                ?disabled=${this.currentPage >= totalPages - 1}
                @click=${() => this.currentPage = totalPages - 1}
              >
                Last
              </button>
            </div>
          </div>
        ` : nothing}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-data-table': CcDataTable;
  }
}

// packages/renderer-angular/src/lib/components/cc-data-table.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

interface Column { key: string; label?: string; sortable?: boolean; type?: string; }

@Component({
  selector: 'cc-data-table',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="cc-data-table">
      @if (searchable) {
        <input type="text" [placeholder]="searchPlaceholder" [(ngModel)]="searchQuery" class="cc-dt-search" />
      }
      @if (filteredData.length === 0) {
        <div class="cc-dt-empty">{{ emptyMessage }}</div>
      } @else {
        <table>
          <thead>
            <tr>
              @for (col of columns; track col.key) {
                <th [class.sortable]="col.sortable" (click)="col.sortable && sort(col.key)">
                  {{ col.label || col.key }}
                  @if (sortColumn === col.key) { <span>{{ sortAsc ? '↑' : '↓' }}</span> }
                </th>
              }
            </tr>
          </thead>
          <tbody>
            @for (row of paginatedData; track $index; let i = $index) {
              <tr [class.alternate]="alternateBackground && i % 2 === 1">
                @for (col of columns; track col.key) {
                  <td>
                    @switch (col.type) {
                      @case ('badge') { <span class="cc-dt-badge">{{ row[col.key] }}</span> }
                      @default { {{ row[col.key] }} }
                    }
                  </td>
                }
              </tr>
            }
          </tbody>
        </table>
        @if (pagination && totalPages > 1) {
          <div class="cc-dt-pagination">
            <button [disabled]="currentPage === 0" (click)="currentPage = currentPage - 1">←</button>
            <span>{{ currentPage + 1 }} / {{ totalPages }}</span>
            <button [disabled]="currentPage >= totalPages - 1" (click)="currentPage = currentPage + 1">→</button>
          </div>
        }
      }
    </div>
  `,
  styles: [`
    .cc-data-table { width: 100%; }
    .cc-dt-search { width: 100%; padding: 0.5rem 0.75rem; border: 1px solid #e2e8f0; border-radius: 0.5rem; margin-bottom: 1rem; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { font-weight: 600; background: #f8fafc; }
    th.sortable { cursor: pointer; }
    th.sortable:hover { background: #e2e8f0; }
    tr.alternate { background: #f8fafc; }
    .cc-dt-empty { padding: 2rem; text-align: center; color: #64748b; }
    .cc-dt-pagination { display: flex; justify-content: center; align-items: center; gap: 1rem; margin-top: 1rem; }
    .cc-dt-pagination button { padding: 0.5rem 1rem; border: 1px solid #e2e8f0; border-radius: 0.25rem; background: white; cursor: pointer; }
    .cc-dt-pagination button:disabled { opacity: 0.5; cursor: not-allowed; }
    .cc-dt-badge { background: #e2e8f0; padding: 0.25rem 0.5rem; border-radius: 9999px; font-size: 0.75rem; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcDataTableComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();

  searchQuery = '';
  sortColumn: string | null = null;
  sortAsc = true;
  currentPage = 0;

  get dataPath(): string | undefined { return this.component['dataPath'] as string; }
  get columns(): Column[] { return (this.component['columns'] as Column[]) ?? []; }
  get pagination(): boolean { return (this.component['pagination'] as boolean) ?? false; }
  get pageSize(): number { return (this.component['pageSize'] as number) ?? 10; }
  get searchable(): boolean { return (this.component['searchable'] as boolean) ?? false; }
  get searchPlaceholder(): string { return (this.component['searchPlaceholder'] as string) ?? 'Search...'; }
  get alternateBackground(): boolean { return (this.component['alternateBackground'] as boolean) ?? false; }
  get emptyMessage(): string { return (this.component['emptyMessage'] as string) ?? 'No data available'; }

  get rawData(): Record<string, unknown>[] {
    if (!this.dataPath) return [];
    const data = getByPointer(this.dataModel, this.dataPath);
    return Array.isArray(data) ? data : [];
  }

  get filteredData(): Record<string, unknown>[] {
    let data = this.rawData;
    if (this.searchQuery) {
      const q = this.searchQuery.toLowerCase();
      data = data.filter(row => Object.values(row).some(v => v?.toString().toLowerCase().includes(q)));
    }
    if (this.sortColumn) {
      data = [...data].sort((a, b) => {
        const av = a[this.sortColumn!], bv = b[this.sortColumn!];
        const cmp = typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av).localeCompare(String(bv));
        return this.sortAsc ? cmp : -cmp;
      });
    }
    return data;
  }

  get totalPages(): number { return Math.ceil(this.filteredData.length / this.pageSize); }

  get paginatedData(): Record<string, unknown>[] {
    if (!this.pagination) return this.filteredData;
    const start = this.currentPage * this.pageSize;
    return this.filteredData.slice(start, start + this.pageSize);
  }

  sort(column: string): void {
    if (this.sortColumn === column) { this.sortAsc = !this.sortAsc; }
    else { this.sortColumn = column; this.sortAsc = true; }
  }
}
