// packages/renderer-lit/src/components/cc-row.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { RowComponent, DataModel, FlexAlignment } from '@claude-canvas/core';

@customElement('cc-row')
export class CcRow extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .row {
      display: flex;
      flex-direction: row;
    }

    .wrap {
      flex-wrap: wrap;
    }
  `;

  @property({ type: Object })
  component!: RowComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getAlignItems(align?: FlexAlignment): string {
    const map: Record<FlexAlignment, string> = {
      start: 'flex-start',
      center: 'center',
      end: 'flex-end',
      stretch: 'stretch',
      spaceBetween: 'space-between',
      spaceAround: 'space-around',
    };
    return map[align ?? 'stretch'];
  }

  private getJustifyContent(justify?: FlexAlignment): string {
    const map: Record<FlexAlignment, string> = {
      start: 'flex-start',
      center: 'center',
      end: 'flex-end',
      stretch: 'stretch',
      spaceBetween: 'space-between',
      spaceAround: 'space-around',
    };
    return map[justify ?? 'start'];
  }

  render() {
    const style = `
      gap: ${this.component.gap ?? 0}px;
      align-items: ${this.getAlignItems(this.component.align)};
      justify-content: ${this.getJustifyContent(this.component.justify)};
    `;

    return html`
      <div class="row ${this.component.wrap ? 'wrap' : ''}" style=${style}>
        <slot></slot>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-row': CcRow;
  }
}

// packages/renderer-angular/src/lib/components/cc-row.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel, Action } from '../types';

@Component({
  selector: 'cc-row',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="cc-row" [style.gap.px]="gap" [style.align-items]="alignItems" [style.justify-content]="justifyContent" [style.flex-wrap]="wrap ? 'wrap' : 'nowrap'">
      <ng-content></ng-content>
    </div>
  `,
  styles: [`
    .cc-row { display: flex; flex-direction: row; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcRowComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();
  @Output() action = new EventEmitter<Action>();

  get gap(): number {
    return (this.component['gap'] as number) ?? 0;
  }

  get align(): string {
    return (this.component['align'] as string) ?? 'center';
  }

  get justify(): string {
    return (this.component['justify'] as string) ?? 'start';
  }

  get wrap(): boolean {
    return (this.component['wrap'] as boolean) ?? false;
  }

  get alignItems(): string {
    const map: Record<string, string> = {
      'start': 'flex-start',
      'end': 'flex-end',
      'center': 'center',
      'stretch': 'stretch',
      'baseline': 'baseline',
    };
    return map[this.align] ?? 'center';
  }

  get justifyContent(): string {
    const map: Record<string, string> = {
      'start': 'flex-start',
      'end': 'flex-end',
      'center': 'center',
      'space-between': 'space-between',
      'space-around': 'space-around',
      'space-evenly': 'space-evenly',
    };
    return map[this.justify] ?? 'flex-start';
  }
}
