// packages/renderer-lit/src/components/cc-skeleton.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { SkeletonComponent, DataModel } from '@claude-canvas/core';

@customElement('cc-skeleton')
export class CcSkeleton extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .skeleton {
      background: var(--cc-skeleton-bg, #e5e7eb);
      position: relative;
      overflow: hidden;
    }

    /* Variants */
    .text {
      height: 1em;
      border-radius: 4px;
    }

    .circular {
      border-radius: 50%;
    }

    .rectangular {
      border-radius: 4px;
    }

    /* Animation: Pulse */
    .pulse {
      animation: pulse 1.5s ease-in-out infinite;
    }

    @keyframes pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.5; }
    }

    /* Animation: Wave */
    .wave::after {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: linear-gradient(
        90deg,
        transparent,
        rgba(255, 255, 255, 0.4),
        transparent
      );
      animation: wave 1.5s linear infinite;
    }

    @keyframes wave {
      0% { transform: translateX(-100%); }
      100% { transform: translateX(100%); }
    }

    .lines {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .line {
      height: 1em;
      border-radius: 4px;
    }

    .line:last-child {
      width: 60%;
    }
  `;

  @property({ type: Object })
  component!: SkeletonComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getWidth(): string {
    const width = this.component.width;
    if (width === undefined) return '100%';
    return typeof width === 'number' ? `${width}px` : width;
  }

  private getHeight(): string {
    const variant = this.component.variant ?? 'rectangular';
    const height = this.component.height;

    if (height !== undefined) {
      return typeof height === 'number' ? `${height}px` : height;
    }

    // Default heights based on variant
    switch (variant) {
      case 'text': return '1em';
      case 'circular': return this.getWidth();
      default: return '100px';
    }
  }

  render() {
    const variant = this.component.variant ?? 'rectangular';
    const animation = this.component.animation ?? 'pulse';
    const lines = this.component.lines ?? 1;
    const width = this.getWidth();
    const height = this.getHeight();

    // For text variant with multiple lines
    if (variant === 'text' && lines > 1) {
      return html`
        <div class="lines" style="width: ${width}">
          ${Array.from({ length: lines }, (_, i) => html`
            <div class="skeleton line ${animation}"
                 style="height: ${height}"></div>
          `)}
        </div>
      `;
    }

    return html`
      <div class="skeleton ${variant} ${animation}"
           style="width: ${width}; height: ${height}">
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-skeleton': CcSkeleton;
  }
}

// packages/renderer-angular/src/lib/components/cc-skeleton.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel } from '../types';

@Component({
  selector: 'cc-skeleton',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (variant === 'text' && lines > 1) {
      <div class="cc-skeleton-lines">
        @for (line of lineArray; track $index; let last = $last) {
          <div class="cc-skeleton cc-skeleton-text" [class]="animationClass" [style.width]="last ? '70%' : width" [style.height.px]="height || 16"></div>
        }
      </div>
    } @else {
      <div class="cc-skeleton" [class]="skeletonClasses" [style.width]="effectiveWidth" [style.height]="effectiveHeight"></div>
    }
  `,
  styles: [`
    .cc-skeleton { background: #e2e8f0; }
    .cc-skeleton-text { border-radius: 0.25rem; }
    .cc-skeleton-circular { border-radius: 50%; }
    .cc-skeleton-rectangular { border-radius: 0; }
    .cc-skeleton-lines { display: flex; flex-direction: column; gap: 0.5rem; }
    .cc-skeleton-pulse { animation: pulse 1.5s ease-in-out infinite; }
    .cc-skeleton-wave { background: linear-gradient(90deg, #e2e8f0 25%, #f1f5f9 50%, #e2e8f0 75%); background-size: 200% 100%; animation: wave 1.5s linear infinite; }
    @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
    @keyframes wave { 0% { background-position: 200% 0; } 100% { background-position: -200% 0; } }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcSkeletonComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};

  get variant(): string { return (this.component['variant'] as string) ?? 'text'; }
  get width(): string | undefined { const w = this.component['width']; return typeof w === 'number' ? `${w}px` : w as string; }
  get height(): number | undefined { return this.component['height'] as number; }
  get lines(): number { return (this.component['lines'] as number) ?? 1; }
  get animation(): string { return (this.component['animation'] as string) ?? 'pulse'; }
  get lineArray(): number[] { return Array.from({ length: this.lines }, (_, i) => i); }
  get animationClass(): string { return this.animation !== 'none' ? `cc-skeleton-${this.animation}` : ''; }
  get effectiveWidth(): string { return this.variant === 'circular' ? `${this.height || 40}px` : this.width || '100%'; }
  get effectiveHeight(): string { return this.variant === 'text' ? `${this.height || 16}px` : `${this.height || (this.variant === 'circular' ? 40 : 100)}px`; }
  get skeletonClasses(): string { return `cc-skeleton-${this.variant} ${this.animationClass}`; }
}
