// packages/renderer-lit/src/components/cc-text-field.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { TextFieldComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-text-field')
export class CcTextField extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .field {
      display: flex;
      flex-direction: column;
      gap: 0.375rem;
    }

    label {
      font-size: 0.875rem;
      font-weight: 500;
      color: var(--cc-text, #333);
    }

    label.required::after {
      content: ' *';
      color: var(--cc-danger, #dc2626);
    }

    input,
    textarea {
      padding: 0.625rem 0.75rem;
      border: 1px solid var(--cc-border, #d1d5db);
      border-radius: 8px;
      font-size: 1rem;
      font-family: inherit;
      transition: border-color 0.15s ease, box-shadow 0.15s ease;
      background: var(--cc-input-bg, white);
      color: var(--cc-text, #333);
    }

    input:focus,
    textarea:focus {
      outline: none;
      border-color: var(--cc-primary, #0066cc);
      box-shadow: 0 0 0 3px var(--cc-primary-light, rgba(0, 102, 204, 0.1));
    }

    input:disabled,
    textarea:disabled {
      background: var(--cc-disabled-bg, #f5f5f5);
      cursor: not-allowed;
    }

    input::placeholder,
    textarea::placeholder {
      color: var(--cc-text-placeholder, #9ca3af);
    }

    textarea {
      resize: vertical;
      min-height: 80px;
    }
  `;

  @property({ type: Object })
  component!: TextFieldComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getValue(): string {
    const value = getByPointer(this.dataModel, this.component.valuePath);
    return String(value ?? '');
  }

  private handleInput(e: Event) {
    const target = e.target as HTMLInputElement | HTMLTextAreaElement;
    const event = new CustomEvent('cc-input', {
      bubbles: true,
      composed: true,
      detail: {
        path: this.component.valuePath,
        value: target.value,
      },
    });
    this.dispatchEvent(event);
  }

  render() {
    const value = this.getValue();

    if (this.component.multiline) {
      return html`
        <div class="field">
          ${this.component.label
            ? html`<label class=${this.component.required ? 'required' : ''}>${this.component.label}</label>`
            : null
          }
          <textarea
            .value=${value}
            placeholder=${this.component.placeholder ?? ''}
            ?disabled=${this.component.disabled}
            ?required=${this.component.required}
            rows=${this.component.rows ?? 3}
            @input=${this.handleInput}
          ></textarea>
        </div>
      `;
    }

    return html`
      <div class="field">
        ${this.component.label
          ? html`<label class=${this.component.required ? 'required' : ''}>${this.component.label}</label>`
          : null
        }
        <input
          type=${this.component.inputType ?? 'text'}
          .value=${value}
          placeholder=${this.component.placeholder ?? ''}
          ?disabled=${this.component.disabled}
          ?required=${this.component.required}
          @input=${this.handleInput}
        />
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-text-field': CcTextField;
  }
}

// packages/renderer-angular/src/lib/components/cc-text-field.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-text-field',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="cc-text-field">
      @if (label) {
        <label class="cc-text-field-label">{{ label }}{{ required ? ' *' : '' }}</label>
      }
      @if (multiline) {
        <textarea
          [value]="value"
          [placeholder]="placeholder"
          [disabled]="disabled"
          [rows]="rows"
          (input)="onInput($event)"
          class="cc-text-field-input"
        ></textarea>
      } @else {
        <input
          [type]="inputType"
          [value]="value"
          [placeholder]="placeholder"
          [disabled]="disabled"
          (input)="onInput($event)"
          class="cc-text-field-input"
        />
      }
    </div>
  `,
  styles: [`
    .cc-text-field { display: flex; flex-direction: column; gap: 0.5rem; }
    .cc-text-field-label { font-weight: 500; font-size: 0.875rem; color: #374151; }
    .cc-text-field-input {
      padding: 0.625rem 0.75rem;
      border: 1px solid #e2e8f0;
      border-radius: 0.5rem;
      font-size: 0.875rem;
      font-family: inherit;
      transition: border-color 0.15s, box-shadow 0.15s;
    }
    .cc-text-field-input:focus {
      outline: none;
      border-color: #6366f1;
      box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
    }
    .cc-text-field-input:disabled { background: #f8fafc; cursor: not-allowed; }
    textarea { resize: vertical; min-height: 5rem; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcTextFieldComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};
  @Output() inputChange = new EventEmitter<{ path: string; value: unknown }>();

  get valuePath(): string | undefined {
    return this.component['valuePath'] as string | undefined;
  }

  get value(): string {
    if (this.valuePath) {
      const v = getByPointer(this.dataModel, this.valuePath);
      return v?.toString() ?? '';
    }
    return '';
  }

  get label(): string | undefined {
    return this.component['label'] as string | undefined;
  }

  get placeholder(): string {
    return (this.component['placeholder'] as string) ?? '';
  }

  get inputType(): string {
    return (this.component['inputType'] as string) ?? 'text';
  }

  get multiline(): boolean {
    return (this.component['multiline'] as boolean) ?? false;
  }

  get rows(): number {
    return (this.component['rows'] as number) ?? 3;
  }

  get required(): boolean {
    return (this.component['required'] as boolean) ?? false;
  }

  get disabled(): boolean {
    return (this.component['disabled'] as boolean) ?? false;
  }

  onInput(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLTextAreaElement;
    if (this.valuePath) {
      this.inputChange.emit({ path: this.valuePath, value: target.value });
    }
  }
}
