// packages/renderer-lit/src/components/cc-video.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { VideoComponent, DataModel } from '@claude-canvas/core';
import { getByPointer } from '@claude-canvas/core';

@customElement('cc-video')
export class CcVideo extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .video-wrapper {
      position: relative;
      width: 100%;
      border-radius: 0.5rem;
      overflow: hidden;
      background: var(--cc-surface-dim, #f3f4f6);
    }

    video {
      width: 100%;
      height: auto;
      display: block;
    }

    .no-source {
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 3rem;
      color: var(--cc-text-secondary, #6b7280);
      font-size: 0.875rem;
    }
  `;

  @property({ type: Object })
  component!: VideoComponent;

  @property({ type: Object })
  dataModel: DataModel = {};

  private getSrc(): string | null {
    if (this.component.src) {
      return this.component.src;
    }
    if (this.component.srcPath) {
      const value = getByPointer(this.dataModel, this.component.srcPath);
      if (value != null && typeof value === 'string') {
        return value;
      }
    }
    return null;
  }

  render() {
    const src = this.getSrc();
    const controls = this.component.controls ?? true;

    if (!src) {
      return html`
        <div class="video-wrapper">
          <div class="no-source">No video source</div>
        </div>
      `;
    }

    return html`
      <div class="video-wrapper">
        <video
          src=${src}
          poster=${this.component.poster || ''}
          ?autoplay=${this.component.autoplay}
          ?controls=${controls}
          ?loop=${this.component.loop}
          ?muted=${this.component.muted}
          playsinline
        ></video>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'cc-video': CcVideo;
  }
}

// packages/renderer-angular/src/lib/components/cc-video.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentDefinition, DataModel } from '../types';
import { getByPointer } from '../utils/json-pointer';

@Component({
  selector: 'cc-video',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (src) {
      <video [src]="src" [poster]="poster" [controls]="controls" [autoplay]="autoplay" [loop]="loop" [muted]="muted" class="cc-video"></video>
    } @else {
      <div class="cc-video-placeholder">No video source</div>
    }
  `,
  styles: [`
    .cc-video { width: 100%; max-width: 100%; border-radius: 0.5rem; }
    .cc-video-placeholder { background: #1e293b; color: #94a3b8; padding: 3rem; text-align: center; border-radius: 0.5rem; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CcVideoComponent {
  @Input() component!: ComponentDefinition;
  @Input() dataModel: DataModel = {};

  get src(): string | undefined { return this.component['srcPath'] ? getByPointer(this.dataModel, this.component['srcPath'] as string)?.toString() : this.component['src'] as string; }
  get poster(): string | undefined { return this.component['poster'] as string; }
  get controls(): boolean { return (this.component['controls'] as boolean) ?? true; }
  get autoplay(): boolean { return (this.component['autoplay'] as boolean) ?? false; }
  get loop(): boolean { return (this.component['loop'] as boolean) ?? false; }
  get muted(): boolean { return (this.component['muted'] as boolean) ?? false; }
}
